// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bilibili/metadata/locale/locale.proto

package bilibili.metadata.locale;

public final class LocaleOuterClass {
  private LocaleOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface LocaleOrBuilder extends
      // @@protoc_insertion_point(interface_extends:bilibili.metadata.locale.Locale)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * App设置的locale
     * </pre>
     *
     * <code>.bilibili.metadata.locale.LocaleIds c_locale = 1;</code>
     * @return Whether the cLocale field is set.
     */
    boolean hasCLocale();
    /**
     * <pre>
     * App设置的locale
     * </pre>
     *
     * <code>.bilibili.metadata.locale.LocaleIds c_locale = 1;</code>
     * @return The cLocale.
     */
    bilibili.metadata.locale.LocaleOuterClass.LocaleIds getCLocale();
    /**
     * <pre>
     * App设置的locale
     * </pre>
     *
     * <code>.bilibili.metadata.locale.LocaleIds c_locale = 1;</code>
     */
    bilibili.metadata.locale.LocaleOuterClass.LocaleIdsOrBuilder getCLocaleOrBuilder();

    /**
     * <pre>
     * 系统默认的locale
     * </pre>
     *
     * <code>.bilibili.metadata.locale.LocaleIds s_locale = 2;</code>
     * @return Whether the sLocale field is set.
     */
    boolean hasSLocale();
    /**
     * <pre>
     * 系统默认的locale
     * </pre>
     *
     * <code>.bilibili.metadata.locale.LocaleIds s_locale = 2;</code>
     * @return The sLocale.
     */
    bilibili.metadata.locale.LocaleOuterClass.LocaleIds getSLocale();
    /**
     * <pre>
     * 系统默认的locale
     * </pre>
     *
     * <code>.bilibili.metadata.locale.LocaleIds s_locale = 2;</code>
     */
    bilibili.metadata.locale.LocaleOuterClass.LocaleIdsOrBuilder getSLocaleOrBuilder();

    /**
     * <pre>
     * sim卡的国家码+运营商码
     * </pre>
     *
     * <code>string sim_code = 3;</code>
     * @return The simCode.
     */
    java.lang.String getSimCode();
    /**
     * <pre>
     * sim卡的国家码+运营商码
     * </pre>
     *
     * <code>string sim_code = 3;</code>
     * @return The bytes for simCode.
     */
    com.google.protobuf.ByteString
        getSimCodeBytes();

    /**
     * <pre>
     * 时区
     * </pre>
     *
     * <code>string timezone = 4;</code>
     * @return The timezone.
     */
    java.lang.String getTimezone();
    /**
     * <pre>
     * 时区
     * </pre>
     *
     * <code>string timezone = 4;</code>
     * @return The bytes for timezone.
     */
    com.google.protobuf.ByteString
        getTimezoneBytes();
  }
  /**
   * <pre>
   * 区域标识
   * gRPC头部:x-bili-locale-bin
   * </pre>
   *
   * Protobuf type {@code bilibili.metadata.locale.Locale}
   */
  public static final class Locale extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:bilibili.metadata.locale.Locale)
      LocaleOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Locale.newBuilder() to construct.
    private Locale(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Locale() {
      simCode_ = "";
      timezone_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Locale();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return bilibili.metadata.locale.LocaleOuterClass.internal_static_bilibili_metadata_locale_Locale_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return bilibili.metadata.locale.LocaleOuterClass.internal_static_bilibili_metadata_locale_Locale_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              bilibili.metadata.locale.LocaleOuterClass.Locale.class, bilibili.metadata.locale.LocaleOuterClass.Locale.Builder.class);
    }

    public static final int C_LOCALE_FIELD_NUMBER = 1;
    private bilibili.metadata.locale.LocaleOuterClass.LocaleIds cLocale_;
    /**
     * <pre>
     * App设置的locale
     * </pre>
     *
     * <code>.bilibili.metadata.locale.LocaleIds c_locale = 1;</code>
     * @return Whether the cLocale field is set.
     */
    @java.lang.Override
    public boolean hasCLocale() {
      return cLocale_ != null;
    }
    /**
     * <pre>
     * App设置的locale
     * </pre>
     *
     * <code>.bilibili.metadata.locale.LocaleIds c_locale = 1;</code>
     * @return The cLocale.
     */
    @java.lang.Override
    public bilibili.metadata.locale.LocaleOuterClass.LocaleIds getCLocale() {
      return cLocale_ == null ? bilibili.metadata.locale.LocaleOuterClass.LocaleIds.getDefaultInstance() : cLocale_;
    }
    /**
     * <pre>
     * App设置的locale
     * </pre>
     *
     * <code>.bilibili.metadata.locale.LocaleIds c_locale = 1;</code>
     */
    @java.lang.Override
    public bilibili.metadata.locale.LocaleOuterClass.LocaleIdsOrBuilder getCLocaleOrBuilder() {
      return getCLocale();
    }

    public static final int S_LOCALE_FIELD_NUMBER = 2;
    private bilibili.metadata.locale.LocaleOuterClass.LocaleIds sLocale_;
    /**
     * <pre>
     * 系统默认的locale
     * </pre>
     *
     * <code>.bilibili.metadata.locale.LocaleIds s_locale = 2;</code>
     * @return Whether the sLocale field is set.
     */
    @java.lang.Override
    public boolean hasSLocale() {
      return sLocale_ != null;
    }
    /**
     * <pre>
     * 系统默认的locale
     * </pre>
     *
     * <code>.bilibili.metadata.locale.LocaleIds s_locale = 2;</code>
     * @return The sLocale.
     */
    @java.lang.Override
    public bilibili.metadata.locale.LocaleOuterClass.LocaleIds getSLocale() {
      return sLocale_ == null ? bilibili.metadata.locale.LocaleOuterClass.LocaleIds.getDefaultInstance() : sLocale_;
    }
    /**
     * <pre>
     * 系统默认的locale
     * </pre>
     *
     * <code>.bilibili.metadata.locale.LocaleIds s_locale = 2;</code>
     */
    @java.lang.Override
    public bilibili.metadata.locale.LocaleOuterClass.LocaleIdsOrBuilder getSLocaleOrBuilder() {
      return getSLocale();
    }

    public static final int SIM_CODE_FIELD_NUMBER = 3;
    private volatile java.lang.Object simCode_;
    /**
     * <pre>
     * sim卡的国家码+运营商码
     * </pre>
     *
     * <code>string sim_code = 3;</code>
     * @return The simCode.
     */
    @java.lang.Override
    public java.lang.String getSimCode() {
      java.lang.Object ref = simCode_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        simCode_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * sim卡的国家码+运营商码
     * </pre>
     *
     * <code>string sim_code = 3;</code>
     * @return The bytes for simCode.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getSimCodeBytes() {
      java.lang.Object ref = simCode_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        simCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TIMEZONE_FIELD_NUMBER = 4;
    private volatile java.lang.Object timezone_;
    /**
     * <pre>
     * 时区
     * </pre>
     *
     * <code>string timezone = 4;</code>
     * @return The timezone.
     */
    @java.lang.Override
    public java.lang.String getTimezone() {
      java.lang.Object ref = timezone_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        timezone_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 时区
     * </pre>
     *
     * <code>string timezone = 4;</code>
     * @return The bytes for timezone.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getTimezoneBytes() {
      java.lang.Object ref = timezone_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        timezone_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (cLocale_ != null) {
        output.writeMessage(1, getCLocale());
      }
      if (sLocale_ != null) {
        output.writeMessage(2, getSLocale());
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(simCode_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, simCode_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(timezone_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, timezone_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (cLocale_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getCLocale());
      }
      if (sLocale_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getSLocale());
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(simCode_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, simCode_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(timezone_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, timezone_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof bilibili.metadata.locale.LocaleOuterClass.Locale)) {
        return super.equals(obj);
      }
      bilibili.metadata.locale.LocaleOuterClass.Locale other = (bilibili.metadata.locale.LocaleOuterClass.Locale) obj;

      if (hasCLocale() != other.hasCLocale()) return false;
      if (hasCLocale()) {
        if (!getCLocale()
            .equals(other.getCLocale())) return false;
      }
      if (hasSLocale() != other.hasSLocale()) return false;
      if (hasSLocale()) {
        if (!getSLocale()
            .equals(other.getSLocale())) return false;
      }
      if (!getSimCode()
          .equals(other.getSimCode())) return false;
      if (!getTimezone()
          .equals(other.getTimezone())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasCLocale()) {
        hash = (37 * hash) + C_LOCALE_FIELD_NUMBER;
        hash = (53 * hash) + getCLocale().hashCode();
      }
      if (hasSLocale()) {
        hash = (37 * hash) + S_LOCALE_FIELD_NUMBER;
        hash = (53 * hash) + getSLocale().hashCode();
      }
      hash = (37 * hash) + SIM_CODE_FIELD_NUMBER;
      hash = (53 * hash) + getSimCode().hashCode();
      hash = (37 * hash) + TIMEZONE_FIELD_NUMBER;
      hash = (53 * hash) + getTimezone().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static bilibili.metadata.locale.LocaleOuterClass.Locale parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static bilibili.metadata.locale.LocaleOuterClass.Locale parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static bilibili.metadata.locale.LocaleOuterClass.Locale parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static bilibili.metadata.locale.LocaleOuterClass.Locale parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static bilibili.metadata.locale.LocaleOuterClass.Locale parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static bilibili.metadata.locale.LocaleOuterClass.Locale parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static bilibili.metadata.locale.LocaleOuterClass.Locale parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static bilibili.metadata.locale.LocaleOuterClass.Locale parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static bilibili.metadata.locale.LocaleOuterClass.Locale parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static bilibili.metadata.locale.LocaleOuterClass.Locale parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static bilibili.metadata.locale.LocaleOuterClass.Locale parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static bilibili.metadata.locale.LocaleOuterClass.Locale parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(bilibili.metadata.locale.LocaleOuterClass.Locale prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * 区域标识
     * gRPC头部:x-bili-locale-bin
     * </pre>
     *
     * Protobuf type {@code bilibili.metadata.locale.Locale}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:bilibili.metadata.locale.Locale)
        bilibili.metadata.locale.LocaleOuterClass.LocaleOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return bilibili.metadata.locale.LocaleOuterClass.internal_static_bilibili_metadata_locale_Locale_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return bilibili.metadata.locale.LocaleOuterClass.internal_static_bilibili_metadata_locale_Locale_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                bilibili.metadata.locale.LocaleOuterClass.Locale.class, bilibili.metadata.locale.LocaleOuterClass.Locale.Builder.class);
      }

      // Construct using bilibili.metadata.locale.LocaleOuterClass.Locale.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (cLocaleBuilder_ == null) {
          cLocale_ = null;
        } else {
          cLocale_ = null;
          cLocaleBuilder_ = null;
        }
        if (sLocaleBuilder_ == null) {
          sLocale_ = null;
        } else {
          sLocale_ = null;
          sLocaleBuilder_ = null;
        }
        simCode_ = "";

        timezone_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return bilibili.metadata.locale.LocaleOuterClass.internal_static_bilibili_metadata_locale_Locale_descriptor;
      }

      @java.lang.Override
      public bilibili.metadata.locale.LocaleOuterClass.Locale getDefaultInstanceForType() {
        return bilibili.metadata.locale.LocaleOuterClass.Locale.getDefaultInstance();
      }

      @java.lang.Override
      public bilibili.metadata.locale.LocaleOuterClass.Locale build() {
        bilibili.metadata.locale.LocaleOuterClass.Locale result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public bilibili.metadata.locale.LocaleOuterClass.Locale buildPartial() {
        bilibili.metadata.locale.LocaleOuterClass.Locale result = new bilibili.metadata.locale.LocaleOuterClass.Locale(this);
        if (cLocaleBuilder_ == null) {
          result.cLocale_ = cLocale_;
        } else {
          result.cLocale_ = cLocaleBuilder_.build();
        }
        if (sLocaleBuilder_ == null) {
          result.sLocale_ = sLocale_;
        } else {
          result.sLocale_ = sLocaleBuilder_.build();
        }
        result.simCode_ = simCode_;
        result.timezone_ = timezone_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof bilibili.metadata.locale.LocaleOuterClass.Locale) {
          return mergeFrom((bilibili.metadata.locale.LocaleOuterClass.Locale)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(bilibili.metadata.locale.LocaleOuterClass.Locale other) {
        if (other == bilibili.metadata.locale.LocaleOuterClass.Locale.getDefaultInstance()) return this;
        if (other.hasCLocale()) {
          mergeCLocale(other.getCLocale());
        }
        if (other.hasSLocale()) {
          mergeSLocale(other.getSLocale());
        }
        if (!other.getSimCode().isEmpty()) {
          simCode_ = other.simCode_;
          onChanged();
        }
        if (!other.getTimezone().isEmpty()) {
          timezone_ = other.timezone_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                input.readMessage(
                    getCLocaleFieldBuilder().getBuilder(),
                    extensionRegistry);

                break;
              } // case 10
              case 18: {
                input.readMessage(
                    getSLocaleFieldBuilder().getBuilder(),
                    extensionRegistry);

                break;
              } // case 18
              case 26: {
                simCode_ = input.readStringRequireUtf8();

                break;
              } // case 26
              case 34: {
                timezone_ = input.readStringRequireUtf8();

                break;
              } // case 34
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }

      private bilibili.metadata.locale.LocaleOuterClass.LocaleIds cLocale_;
      private com.google.protobuf.SingleFieldBuilderV3<
          bilibili.metadata.locale.LocaleOuterClass.LocaleIds, bilibili.metadata.locale.LocaleOuterClass.LocaleIds.Builder, bilibili.metadata.locale.LocaleOuterClass.LocaleIdsOrBuilder> cLocaleBuilder_;
      /**
       * <pre>
       * App设置的locale
       * </pre>
       *
       * <code>.bilibili.metadata.locale.LocaleIds c_locale = 1;</code>
       * @return Whether the cLocale field is set.
       */
      public boolean hasCLocale() {
        return cLocaleBuilder_ != null || cLocale_ != null;
      }
      /**
       * <pre>
       * App设置的locale
       * </pre>
       *
       * <code>.bilibili.metadata.locale.LocaleIds c_locale = 1;</code>
       * @return The cLocale.
       */
      public bilibili.metadata.locale.LocaleOuterClass.LocaleIds getCLocale() {
        if (cLocaleBuilder_ == null) {
          return cLocale_ == null ? bilibili.metadata.locale.LocaleOuterClass.LocaleIds.getDefaultInstance() : cLocale_;
        } else {
          return cLocaleBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       * App设置的locale
       * </pre>
       *
       * <code>.bilibili.metadata.locale.LocaleIds c_locale = 1;</code>
       */
      public Builder setCLocale(bilibili.metadata.locale.LocaleOuterClass.LocaleIds value) {
        if (cLocaleBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          cLocale_ = value;
          onChanged();
        } else {
          cLocaleBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <pre>
       * App设置的locale
       * </pre>
       *
       * <code>.bilibili.metadata.locale.LocaleIds c_locale = 1;</code>
       */
      public Builder setCLocale(
          bilibili.metadata.locale.LocaleOuterClass.LocaleIds.Builder builderForValue) {
        if (cLocaleBuilder_ == null) {
          cLocale_ = builderForValue.build();
          onChanged();
        } else {
          cLocaleBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <pre>
       * App设置的locale
       * </pre>
       *
       * <code>.bilibili.metadata.locale.LocaleIds c_locale = 1;</code>
       */
      public Builder mergeCLocale(bilibili.metadata.locale.LocaleOuterClass.LocaleIds value) {
        if (cLocaleBuilder_ == null) {
          if (cLocale_ != null) {
            cLocale_ =
              bilibili.metadata.locale.LocaleOuterClass.LocaleIds.newBuilder(cLocale_).mergeFrom(value).buildPartial();
          } else {
            cLocale_ = value;
          }
          onChanged();
        } else {
          cLocaleBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <pre>
       * App设置的locale
       * </pre>
       *
       * <code>.bilibili.metadata.locale.LocaleIds c_locale = 1;</code>
       */
      public Builder clearCLocale() {
        if (cLocaleBuilder_ == null) {
          cLocale_ = null;
          onChanged();
        } else {
          cLocale_ = null;
          cLocaleBuilder_ = null;
        }

        return this;
      }
      /**
       * <pre>
       * App设置的locale
       * </pre>
       *
       * <code>.bilibili.metadata.locale.LocaleIds c_locale = 1;</code>
       */
      public bilibili.metadata.locale.LocaleOuterClass.LocaleIds.Builder getCLocaleBuilder() {
        
        onChanged();
        return getCLocaleFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       * App设置的locale
       * </pre>
       *
       * <code>.bilibili.metadata.locale.LocaleIds c_locale = 1;</code>
       */
      public bilibili.metadata.locale.LocaleOuterClass.LocaleIdsOrBuilder getCLocaleOrBuilder() {
        if (cLocaleBuilder_ != null) {
          return cLocaleBuilder_.getMessageOrBuilder();
        } else {
          return cLocale_ == null ?
              bilibili.metadata.locale.LocaleOuterClass.LocaleIds.getDefaultInstance() : cLocale_;
        }
      }
      /**
       * <pre>
       * App设置的locale
       * </pre>
       *
       * <code>.bilibili.metadata.locale.LocaleIds c_locale = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          bilibili.metadata.locale.LocaleOuterClass.LocaleIds, bilibili.metadata.locale.LocaleOuterClass.LocaleIds.Builder, bilibili.metadata.locale.LocaleOuterClass.LocaleIdsOrBuilder> 
          getCLocaleFieldBuilder() {
        if (cLocaleBuilder_ == null) {
          cLocaleBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              bilibili.metadata.locale.LocaleOuterClass.LocaleIds, bilibili.metadata.locale.LocaleOuterClass.LocaleIds.Builder, bilibili.metadata.locale.LocaleOuterClass.LocaleIdsOrBuilder>(
                  getCLocale(),
                  getParentForChildren(),
                  isClean());
          cLocale_ = null;
        }
        return cLocaleBuilder_;
      }

      private bilibili.metadata.locale.LocaleOuterClass.LocaleIds sLocale_;
      private com.google.protobuf.SingleFieldBuilderV3<
          bilibili.metadata.locale.LocaleOuterClass.LocaleIds, bilibili.metadata.locale.LocaleOuterClass.LocaleIds.Builder, bilibili.metadata.locale.LocaleOuterClass.LocaleIdsOrBuilder> sLocaleBuilder_;
      /**
       * <pre>
       * 系统默认的locale
       * </pre>
       *
       * <code>.bilibili.metadata.locale.LocaleIds s_locale = 2;</code>
       * @return Whether the sLocale field is set.
       */
      public boolean hasSLocale() {
        return sLocaleBuilder_ != null || sLocale_ != null;
      }
      /**
       * <pre>
       * 系统默认的locale
       * </pre>
       *
       * <code>.bilibili.metadata.locale.LocaleIds s_locale = 2;</code>
       * @return The sLocale.
       */
      public bilibili.metadata.locale.LocaleOuterClass.LocaleIds getSLocale() {
        if (sLocaleBuilder_ == null) {
          return sLocale_ == null ? bilibili.metadata.locale.LocaleOuterClass.LocaleIds.getDefaultInstance() : sLocale_;
        } else {
          return sLocaleBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       * 系统默认的locale
       * </pre>
       *
       * <code>.bilibili.metadata.locale.LocaleIds s_locale = 2;</code>
       */
      public Builder setSLocale(bilibili.metadata.locale.LocaleOuterClass.LocaleIds value) {
        if (sLocaleBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          sLocale_ = value;
          onChanged();
        } else {
          sLocaleBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <pre>
       * 系统默认的locale
       * </pre>
       *
       * <code>.bilibili.metadata.locale.LocaleIds s_locale = 2;</code>
       */
      public Builder setSLocale(
          bilibili.metadata.locale.LocaleOuterClass.LocaleIds.Builder builderForValue) {
        if (sLocaleBuilder_ == null) {
          sLocale_ = builderForValue.build();
          onChanged();
        } else {
          sLocaleBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <pre>
       * 系统默认的locale
       * </pre>
       *
       * <code>.bilibili.metadata.locale.LocaleIds s_locale = 2;</code>
       */
      public Builder mergeSLocale(bilibili.metadata.locale.LocaleOuterClass.LocaleIds value) {
        if (sLocaleBuilder_ == null) {
          if (sLocale_ != null) {
            sLocale_ =
              bilibili.metadata.locale.LocaleOuterClass.LocaleIds.newBuilder(sLocale_).mergeFrom(value).buildPartial();
          } else {
            sLocale_ = value;
          }
          onChanged();
        } else {
          sLocaleBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <pre>
       * 系统默认的locale
       * </pre>
       *
       * <code>.bilibili.metadata.locale.LocaleIds s_locale = 2;</code>
       */
      public Builder clearSLocale() {
        if (sLocaleBuilder_ == null) {
          sLocale_ = null;
          onChanged();
        } else {
          sLocale_ = null;
          sLocaleBuilder_ = null;
        }

        return this;
      }
      /**
       * <pre>
       * 系统默认的locale
       * </pre>
       *
       * <code>.bilibili.metadata.locale.LocaleIds s_locale = 2;</code>
       */
      public bilibili.metadata.locale.LocaleOuterClass.LocaleIds.Builder getSLocaleBuilder() {
        
        onChanged();
        return getSLocaleFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       * 系统默认的locale
       * </pre>
       *
       * <code>.bilibili.metadata.locale.LocaleIds s_locale = 2;</code>
       */
      public bilibili.metadata.locale.LocaleOuterClass.LocaleIdsOrBuilder getSLocaleOrBuilder() {
        if (sLocaleBuilder_ != null) {
          return sLocaleBuilder_.getMessageOrBuilder();
        } else {
          return sLocale_ == null ?
              bilibili.metadata.locale.LocaleOuterClass.LocaleIds.getDefaultInstance() : sLocale_;
        }
      }
      /**
       * <pre>
       * 系统默认的locale
       * </pre>
       *
       * <code>.bilibili.metadata.locale.LocaleIds s_locale = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          bilibili.metadata.locale.LocaleOuterClass.LocaleIds, bilibili.metadata.locale.LocaleOuterClass.LocaleIds.Builder, bilibili.metadata.locale.LocaleOuterClass.LocaleIdsOrBuilder> 
          getSLocaleFieldBuilder() {
        if (sLocaleBuilder_ == null) {
          sLocaleBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              bilibili.metadata.locale.LocaleOuterClass.LocaleIds, bilibili.metadata.locale.LocaleOuterClass.LocaleIds.Builder, bilibili.metadata.locale.LocaleOuterClass.LocaleIdsOrBuilder>(
                  getSLocale(),
                  getParentForChildren(),
                  isClean());
          sLocale_ = null;
        }
        return sLocaleBuilder_;
      }

      private java.lang.Object simCode_ = "";
      /**
       * <pre>
       * sim卡的国家码+运营商码
       * </pre>
       *
       * <code>string sim_code = 3;</code>
       * @return The simCode.
       */
      public java.lang.String getSimCode() {
        java.lang.Object ref = simCode_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          simCode_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * sim卡的国家码+运营商码
       * </pre>
       *
       * <code>string sim_code = 3;</code>
       * @return The bytes for simCode.
       */
      public com.google.protobuf.ByteString
          getSimCodeBytes() {
        java.lang.Object ref = simCode_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          simCode_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * sim卡的国家码+运营商码
       * </pre>
       *
       * <code>string sim_code = 3;</code>
       * @param value The simCode to set.
       * @return This builder for chaining.
       */
      public Builder setSimCode(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        simCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * sim卡的国家码+运营商码
       * </pre>
       *
       * <code>string sim_code = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearSimCode() {
        
        simCode_ = getDefaultInstance().getSimCode();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * sim卡的国家码+运营商码
       * </pre>
       *
       * <code>string sim_code = 3;</code>
       * @param value The bytes for simCode to set.
       * @return This builder for chaining.
       */
      public Builder setSimCodeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        simCode_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object timezone_ = "";
      /**
       * <pre>
       * 时区
       * </pre>
       *
       * <code>string timezone = 4;</code>
       * @return The timezone.
       */
      public java.lang.String getTimezone() {
        java.lang.Object ref = timezone_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          timezone_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 时区
       * </pre>
       *
       * <code>string timezone = 4;</code>
       * @return The bytes for timezone.
       */
      public com.google.protobuf.ByteString
          getTimezoneBytes() {
        java.lang.Object ref = timezone_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          timezone_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 时区
       * </pre>
       *
       * <code>string timezone = 4;</code>
       * @param value The timezone to set.
       * @return This builder for chaining.
       */
      public Builder setTimezone(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        timezone_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 时区
       * </pre>
       *
       * <code>string timezone = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearTimezone() {
        
        timezone_ = getDefaultInstance().getTimezone();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 时区
       * </pre>
       *
       * <code>string timezone = 4;</code>
       * @param value The bytes for timezone to set.
       * @return This builder for chaining.
       */
      public Builder setTimezoneBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        timezone_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:bilibili.metadata.locale.Locale)
    }

    // @@protoc_insertion_point(class_scope:bilibili.metadata.locale.Locale)
    private static final bilibili.metadata.locale.LocaleOuterClass.Locale DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new bilibili.metadata.locale.LocaleOuterClass.Locale();
    }

    public static bilibili.metadata.locale.LocaleOuterClass.Locale getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Locale>
        PARSER = new com.google.protobuf.AbstractParser<Locale>() {
      @java.lang.Override
      public Locale parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Locale> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Locale> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public bilibili.metadata.locale.LocaleOuterClass.Locale getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface LocaleIdsOrBuilder extends
      // @@protoc_insertion_point(interface_extends:bilibili.metadata.locale.LocaleIds)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * A language designator is a code that represents a language.
     * </pre>
     *
     * <code>string language = 1;</code>
     * @return The language.
     */
    java.lang.String getLanguage();
    /**
     * <pre>
     * A language designator is a code that represents a language.
     * </pre>
     *
     * <code>string language = 1;</code>
     * @return The bytes for language.
     */
    com.google.protobuf.ByteString
        getLanguageBytes();

    /**
     * <pre>
     * Writing systems.
     * </pre>
     *
     * <code>string script = 2;</code>
     * @return The script.
     */
    java.lang.String getScript();
    /**
     * <pre>
     * Writing systems.
     * </pre>
     *
     * <code>string script = 2;</code>
     * @return The bytes for script.
     */
    com.google.protobuf.ByteString
        getScriptBytes();

    /**
     * <pre>
     * A region designator is a code that represents a country or an area.
     * </pre>
     *
     * <code>string region = 3;</code>
     * @return The region.
     */
    java.lang.String getRegion();
    /**
     * <pre>
     * A region designator is a code that represents a country or an area.
     * </pre>
     *
     * <code>string region = 3;</code>
     * @return The bytes for region.
     */
    com.google.protobuf.ByteString
        getRegionBytes();
  }
  /**
   * <pre>
   * Defined by https://developer.apple.com/library/archive/documentation/MacOSX/Conceptual/BPInternational/LanguageandLocaleIDs/LanguageandLocaleIDs.html
   * </pre>
   *
   * Protobuf type {@code bilibili.metadata.locale.LocaleIds}
   */
  public static final class LocaleIds extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:bilibili.metadata.locale.LocaleIds)
      LocaleIdsOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use LocaleIds.newBuilder() to construct.
    private LocaleIds(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private LocaleIds() {
      language_ = "";
      script_ = "";
      region_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new LocaleIds();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return bilibili.metadata.locale.LocaleOuterClass.internal_static_bilibili_metadata_locale_LocaleIds_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return bilibili.metadata.locale.LocaleOuterClass.internal_static_bilibili_metadata_locale_LocaleIds_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              bilibili.metadata.locale.LocaleOuterClass.LocaleIds.class, bilibili.metadata.locale.LocaleOuterClass.LocaleIds.Builder.class);
    }

    public static final int LANGUAGE_FIELD_NUMBER = 1;
    private volatile java.lang.Object language_;
    /**
     * <pre>
     * A language designator is a code that represents a language.
     * </pre>
     *
     * <code>string language = 1;</code>
     * @return The language.
     */
    @java.lang.Override
    public java.lang.String getLanguage() {
      java.lang.Object ref = language_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        language_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * A language designator is a code that represents a language.
     * </pre>
     *
     * <code>string language = 1;</code>
     * @return The bytes for language.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getLanguageBytes() {
      java.lang.Object ref = language_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        language_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SCRIPT_FIELD_NUMBER = 2;
    private volatile java.lang.Object script_;
    /**
     * <pre>
     * Writing systems.
     * </pre>
     *
     * <code>string script = 2;</code>
     * @return The script.
     */
    @java.lang.Override
    public java.lang.String getScript() {
      java.lang.Object ref = script_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        script_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * Writing systems.
     * </pre>
     *
     * <code>string script = 2;</code>
     * @return The bytes for script.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getScriptBytes() {
      java.lang.Object ref = script_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        script_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int REGION_FIELD_NUMBER = 3;
    private volatile java.lang.Object region_;
    /**
     * <pre>
     * A region designator is a code that represents a country or an area.
     * </pre>
     *
     * <code>string region = 3;</code>
     * @return The region.
     */
    @java.lang.Override
    public java.lang.String getRegion() {
      java.lang.Object ref = region_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        region_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * A region designator is a code that represents a country or an area.
     * </pre>
     *
     * <code>string region = 3;</code>
     * @return The bytes for region.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getRegionBytes() {
      java.lang.Object ref = region_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        region_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(language_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, language_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(script_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, script_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(region_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, region_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(language_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, language_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(script_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, script_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(region_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, region_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof bilibili.metadata.locale.LocaleOuterClass.LocaleIds)) {
        return super.equals(obj);
      }
      bilibili.metadata.locale.LocaleOuterClass.LocaleIds other = (bilibili.metadata.locale.LocaleOuterClass.LocaleIds) obj;

      if (!getLanguage()
          .equals(other.getLanguage())) return false;
      if (!getScript()
          .equals(other.getScript())) return false;
      if (!getRegion()
          .equals(other.getRegion())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + LANGUAGE_FIELD_NUMBER;
      hash = (53 * hash) + getLanguage().hashCode();
      hash = (37 * hash) + SCRIPT_FIELD_NUMBER;
      hash = (53 * hash) + getScript().hashCode();
      hash = (37 * hash) + REGION_FIELD_NUMBER;
      hash = (53 * hash) + getRegion().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static bilibili.metadata.locale.LocaleOuterClass.LocaleIds parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static bilibili.metadata.locale.LocaleOuterClass.LocaleIds parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static bilibili.metadata.locale.LocaleOuterClass.LocaleIds parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static bilibili.metadata.locale.LocaleOuterClass.LocaleIds parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static bilibili.metadata.locale.LocaleOuterClass.LocaleIds parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static bilibili.metadata.locale.LocaleOuterClass.LocaleIds parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static bilibili.metadata.locale.LocaleOuterClass.LocaleIds parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static bilibili.metadata.locale.LocaleOuterClass.LocaleIds parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static bilibili.metadata.locale.LocaleOuterClass.LocaleIds parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static bilibili.metadata.locale.LocaleOuterClass.LocaleIds parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static bilibili.metadata.locale.LocaleOuterClass.LocaleIds parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static bilibili.metadata.locale.LocaleOuterClass.LocaleIds parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(bilibili.metadata.locale.LocaleOuterClass.LocaleIds prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * Defined by https://developer.apple.com/library/archive/documentation/MacOSX/Conceptual/BPInternational/LanguageandLocaleIDs/LanguageandLocaleIDs.html
     * </pre>
     *
     * Protobuf type {@code bilibili.metadata.locale.LocaleIds}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:bilibili.metadata.locale.LocaleIds)
        bilibili.metadata.locale.LocaleOuterClass.LocaleIdsOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return bilibili.metadata.locale.LocaleOuterClass.internal_static_bilibili_metadata_locale_LocaleIds_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return bilibili.metadata.locale.LocaleOuterClass.internal_static_bilibili_metadata_locale_LocaleIds_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                bilibili.metadata.locale.LocaleOuterClass.LocaleIds.class, bilibili.metadata.locale.LocaleOuterClass.LocaleIds.Builder.class);
      }

      // Construct using bilibili.metadata.locale.LocaleOuterClass.LocaleIds.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        language_ = "";

        script_ = "";

        region_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return bilibili.metadata.locale.LocaleOuterClass.internal_static_bilibili_metadata_locale_LocaleIds_descriptor;
      }

      @java.lang.Override
      public bilibili.metadata.locale.LocaleOuterClass.LocaleIds getDefaultInstanceForType() {
        return bilibili.metadata.locale.LocaleOuterClass.LocaleIds.getDefaultInstance();
      }

      @java.lang.Override
      public bilibili.metadata.locale.LocaleOuterClass.LocaleIds build() {
        bilibili.metadata.locale.LocaleOuterClass.LocaleIds result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public bilibili.metadata.locale.LocaleOuterClass.LocaleIds buildPartial() {
        bilibili.metadata.locale.LocaleOuterClass.LocaleIds result = new bilibili.metadata.locale.LocaleOuterClass.LocaleIds(this);
        result.language_ = language_;
        result.script_ = script_;
        result.region_ = region_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof bilibili.metadata.locale.LocaleOuterClass.LocaleIds) {
          return mergeFrom((bilibili.metadata.locale.LocaleOuterClass.LocaleIds)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(bilibili.metadata.locale.LocaleOuterClass.LocaleIds other) {
        if (other == bilibili.metadata.locale.LocaleOuterClass.LocaleIds.getDefaultInstance()) return this;
        if (!other.getLanguage().isEmpty()) {
          language_ = other.language_;
          onChanged();
        }
        if (!other.getScript().isEmpty()) {
          script_ = other.script_;
          onChanged();
        }
        if (!other.getRegion().isEmpty()) {
          region_ = other.region_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                language_ = input.readStringRequireUtf8();

                break;
              } // case 10
              case 18: {
                script_ = input.readStringRequireUtf8();

                break;
              } // case 18
              case 26: {
                region_ = input.readStringRequireUtf8();

                break;
              } // case 26
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }

      private java.lang.Object language_ = "";
      /**
       * <pre>
       * A language designator is a code that represents a language.
       * </pre>
       *
       * <code>string language = 1;</code>
       * @return The language.
       */
      public java.lang.String getLanguage() {
        java.lang.Object ref = language_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          language_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * A language designator is a code that represents a language.
       * </pre>
       *
       * <code>string language = 1;</code>
       * @return The bytes for language.
       */
      public com.google.protobuf.ByteString
          getLanguageBytes() {
        java.lang.Object ref = language_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          language_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * A language designator is a code that represents a language.
       * </pre>
       *
       * <code>string language = 1;</code>
       * @param value The language to set.
       * @return This builder for chaining.
       */
      public Builder setLanguage(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        language_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * A language designator is a code that represents a language.
       * </pre>
       *
       * <code>string language = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearLanguage() {
        
        language_ = getDefaultInstance().getLanguage();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * A language designator is a code that represents a language.
       * </pre>
       *
       * <code>string language = 1;</code>
       * @param value The bytes for language to set.
       * @return This builder for chaining.
       */
      public Builder setLanguageBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        language_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object script_ = "";
      /**
       * <pre>
       * Writing systems.
       * </pre>
       *
       * <code>string script = 2;</code>
       * @return The script.
       */
      public java.lang.String getScript() {
        java.lang.Object ref = script_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          script_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * Writing systems.
       * </pre>
       *
       * <code>string script = 2;</code>
       * @return The bytes for script.
       */
      public com.google.protobuf.ByteString
          getScriptBytes() {
        java.lang.Object ref = script_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          script_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * Writing systems.
       * </pre>
       *
       * <code>string script = 2;</code>
       * @param value The script to set.
       * @return This builder for chaining.
       */
      public Builder setScript(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        script_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Writing systems.
       * </pre>
       *
       * <code>string script = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearScript() {
        
        script_ = getDefaultInstance().getScript();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Writing systems.
       * </pre>
       *
       * <code>string script = 2;</code>
       * @param value The bytes for script to set.
       * @return This builder for chaining.
       */
      public Builder setScriptBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        script_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object region_ = "";
      /**
       * <pre>
       * A region designator is a code that represents a country or an area.
       * </pre>
       *
       * <code>string region = 3;</code>
       * @return The region.
       */
      public java.lang.String getRegion() {
        java.lang.Object ref = region_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          region_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * A region designator is a code that represents a country or an area.
       * </pre>
       *
       * <code>string region = 3;</code>
       * @return The bytes for region.
       */
      public com.google.protobuf.ByteString
          getRegionBytes() {
        java.lang.Object ref = region_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          region_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * A region designator is a code that represents a country or an area.
       * </pre>
       *
       * <code>string region = 3;</code>
       * @param value The region to set.
       * @return This builder for chaining.
       */
      public Builder setRegion(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        region_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * A region designator is a code that represents a country or an area.
       * </pre>
       *
       * <code>string region = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearRegion() {
        
        region_ = getDefaultInstance().getRegion();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * A region designator is a code that represents a country or an area.
       * </pre>
       *
       * <code>string region = 3;</code>
       * @param value The bytes for region to set.
       * @return This builder for chaining.
       */
      public Builder setRegionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        region_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:bilibili.metadata.locale.LocaleIds)
    }

    // @@protoc_insertion_point(class_scope:bilibili.metadata.locale.LocaleIds)
    private static final bilibili.metadata.locale.LocaleOuterClass.LocaleIds DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new bilibili.metadata.locale.LocaleOuterClass.LocaleIds();
    }

    public static bilibili.metadata.locale.LocaleOuterClass.LocaleIds getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<LocaleIds>
        PARSER = new com.google.protobuf.AbstractParser<LocaleIds>() {
      @java.lang.Override
      public LocaleIds parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<LocaleIds> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<LocaleIds> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public bilibili.metadata.locale.LocaleOuterClass.LocaleIds getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bilibili_metadata_locale_Locale_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_bilibili_metadata_locale_Locale_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bilibili_metadata_locale_LocaleIds_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_bilibili_metadata_locale_LocaleIds_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n%bilibili/metadata/locale/locale.proto\022" +
      "\030bilibili.metadata.locale\"\232\001\n\006Locale\0225\n\010" +
      "c_locale\030\001 \001(\0132#.bilibili.metadata.local" +
      "e.LocaleIds\0225\n\010s_locale\030\002 \001(\0132#.bilibili" +
      ".metadata.locale.LocaleIds\022\020\n\010sim_code\030\003" +
      " \001(\t\022\020\n\010timezone\030\004 \001(\t\"=\n\tLocaleIds\022\020\n\010l" +
      "anguage\030\001 \001(\t\022\016\n\006script\030\002 \001(\t\022\016\n\006region\030" +
      "\003 \001(\tb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_bilibili_metadata_locale_Locale_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_bilibili_metadata_locale_Locale_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_bilibili_metadata_locale_Locale_descriptor,
        new java.lang.String[] { "CLocale", "SLocale", "SimCode", "Timezone", });
    internal_static_bilibili_metadata_locale_LocaleIds_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_bilibili_metadata_locale_LocaleIds_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_bilibili_metadata_locale_LocaleIds_descriptor,
        new java.lang.String[] { "Language", "Script", "Region", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
