// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bilibili/broadcast/v2/laser.proto

package bilibili.broadcast.v2;

public final class LaserOuterClass {
  private LaserOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface LaserEventRespOrBuilder extends
      // @@protoc_insertion_point(interface_extends:bilibili.broadcast.v2.LaserEventResp)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 任务id
     * </pre>
     *
     * <code>int64 taskid = 1;</code>
     * @return The taskid.
     */
    long getTaskid();

    /**
     * <pre>
     * 指令名
     * </pre>
     *
     * <code>string action = 2;</code>
     * @return The action.
     */
    java.lang.String getAction();
    /**
     * <pre>
     * 指令名
     * </pre>
     *
     * <code>string action = 2;</code>
     * @return The bytes for action.
     */
    com.google.protobuf.ByteString
        getActionBytes();

    /**
     * <pre>
     * 指令参数json字符串
     * </pre>
     *
     * <code>string params = 3;</code>
     * @return The params.
     */
    java.lang.String getParams();
    /**
     * <pre>
     * 指令参数json字符串
     * </pre>
     *
     * <code>string params = 3;</code>
     * @return The bytes for params.
     */
    com.google.protobuf.ByteString
        getParamsBytes();
  }
  /**
   * <pre>
   * 服务端下发Laser事件
   * </pre>
   *
   * Protobuf type {@code bilibili.broadcast.v2.LaserEventResp}
   */
  public static final class LaserEventResp extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:bilibili.broadcast.v2.LaserEventResp)
      LaserEventRespOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use LaserEventResp.newBuilder() to construct.
    private LaserEventResp(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private LaserEventResp() {
      action_ = "";
      params_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new LaserEventResp();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return bilibili.broadcast.v2.LaserOuterClass.internal_static_bilibili_broadcast_v2_LaserEventResp_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return bilibili.broadcast.v2.LaserOuterClass.internal_static_bilibili_broadcast_v2_LaserEventResp_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              bilibili.broadcast.v2.LaserOuterClass.LaserEventResp.class, bilibili.broadcast.v2.LaserOuterClass.LaserEventResp.Builder.class);
    }

    public static final int TASKID_FIELD_NUMBER = 1;
    private long taskid_;
    /**
     * <pre>
     * 任务id
     * </pre>
     *
     * <code>int64 taskid = 1;</code>
     * @return The taskid.
     */
    @java.lang.Override
    public long getTaskid() {
      return taskid_;
    }

    public static final int ACTION_FIELD_NUMBER = 2;
    private volatile java.lang.Object action_;
    /**
     * <pre>
     * 指令名
     * </pre>
     *
     * <code>string action = 2;</code>
     * @return The action.
     */
    @java.lang.Override
    public java.lang.String getAction() {
      java.lang.Object ref = action_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        action_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 指令名
     * </pre>
     *
     * <code>string action = 2;</code>
     * @return The bytes for action.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getActionBytes() {
      java.lang.Object ref = action_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        action_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PARAMS_FIELD_NUMBER = 3;
    private volatile java.lang.Object params_;
    /**
     * <pre>
     * 指令参数json字符串
     * </pre>
     *
     * <code>string params = 3;</code>
     * @return The params.
     */
    @java.lang.Override
    public java.lang.String getParams() {
      java.lang.Object ref = params_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        params_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 指令参数json字符串
     * </pre>
     *
     * <code>string params = 3;</code>
     * @return The bytes for params.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getParamsBytes() {
      java.lang.Object ref = params_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        params_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (taskid_ != 0L) {
        output.writeInt64(1, taskid_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(action_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, action_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(params_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, params_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (taskid_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, taskid_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(action_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, action_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(params_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, params_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof bilibili.broadcast.v2.LaserOuterClass.LaserEventResp)) {
        return super.equals(obj);
      }
      bilibili.broadcast.v2.LaserOuterClass.LaserEventResp other = (bilibili.broadcast.v2.LaserOuterClass.LaserEventResp) obj;

      if (getTaskid()
          != other.getTaskid()) return false;
      if (!getAction()
          .equals(other.getAction())) return false;
      if (!getParams()
          .equals(other.getParams())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TASKID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTaskid());
      hash = (37 * hash) + ACTION_FIELD_NUMBER;
      hash = (53 * hash) + getAction().hashCode();
      hash = (37 * hash) + PARAMS_FIELD_NUMBER;
      hash = (53 * hash) + getParams().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static bilibili.broadcast.v2.LaserOuterClass.LaserEventResp parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static bilibili.broadcast.v2.LaserOuterClass.LaserEventResp parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static bilibili.broadcast.v2.LaserOuterClass.LaserEventResp parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static bilibili.broadcast.v2.LaserOuterClass.LaserEventResp parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static bilibili.broadcast.v2.LaserOuterClass.LaserEventResp parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static bilibili.broadcast.v2.LaserOuterClass.LaserEventResp parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static bilibili.broadcast.v2.LaserOuterClass.LaserEventResp parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static bilibili.broadcast.v2.LaserOuterClass.LaserEventResp parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static bilibili.broadcast.v2.LaserOuterClass.LaserEventResp parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static bilibili.broadcast.v2.LaserOuterClass.LaserEventResp parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static bilibili.broadcast.v2.LaserOuterClass.LaserEventResp parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static bilibili.broadcast.v2.LaserOuterClass.LaserEventResp parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(bilibili.broadcast.v2.LaserOuterClass.LaserEventResp prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * 服务端下发Laser事件
     * </pre>
     *
     * Protobuf type {@code bilibili.broadcast.v2.LaserEventResp}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:bilibili.broadcast.v2.LaserEventResp)
        bilibili.broadcast.v2.LaserOuterClass.LaserEventRespOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return bilibili.broadcast.v2.LaserOuterClass.internal_static_bilibili_broadcast_v2_LaserEventResp_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return bilibili.broadcast.v2.LaserOuterClass.internal_static_bilibili_broadcast_v2_LaserEventResp_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                bilibili.broadcast.v2.LaserOuterClass.LaserEventResp.class, bilibili.broadcast.v2.LaserOuterClass.LaserEventResp.Builder.class);
      }

      // Construct using bilibili.broadcast.v2.LaserOuterClass.LaserEventResp.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        taskid_ = 0L;

        action_ = "";

        params_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return bilibili.broadcast.v2.LaserOuterClass.internal_static_bilibili_broadcast_v2_LaserEventResp_descriptor;
      }

      @java.lang.Override
      public bilibili.broadcast.v2.LaserOuterClass.LaserEventResp getDefaultInstanceForType() {
        return bilibili.broadcast.v2.LaserOuterClass.LaserEventResp.getDefaultInstance();
      }

      @java.lang.Override
      public bilibili.broadcast.v2.LaserOuterClass.LaserEventResp build() {
        bilibili.broadcast.v2.LaserOuterClass.LaserEventResp result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public bilibili.broadcast.v2.LaserOuterClass.LaserEventResp buildPartial() {
        bilibili.broadcast.v2.LaserOuterClass.LaserEventResp result = new bilibili.broadcast.v2.LaserOuterClass.LaserEventResp(this);
        result.taskid_ = taskid_;
        result.action_ = action_;
        result.params_ = params_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof bilibili.broadcast.v2.LaserOuterClass.LaserEventResp) {
          return mergeFrom((bilibili.broadcast.v2.LaserOuterClass.LaserEventResp)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(bilibili.broadcast.v2.LaserOuterClass.LaserEventResp other) {
        if (other == bilibili.broadcast.v2.LaserOuterClass.LaserEventResp.getDefaultInstance()) return this;
        if (other.getTaskid() != 0L) {
          setTaskid(other.getTaskid());
        }
        if (!other.getAction().isEmpty()) {
          action_ = other.action_;
          onChanged();
        }
        if (!other.getParams().isEmpty()) {
          params_ = other.params_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                taskid_ = input.readInt64();

                break;
              } // case 8
              case 18: {
                action_ = input.readStringRequireUtf8();

                break;
              } // case 18
              case 26: {
                params_ = input.readStringRequireUtf8();

                break;
              } // case 26
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }

      private long taskid_ ;
      /**
       * <pre>
       * 任务id
       * </pre>
       *
       * <code>int64 taskid = 1;</code>
       * @return The taskid.
       */
      @java.lang.Override
      public long getTaskid() {
        return taskid_;
      }
      /**
       * <pre>
       * 任务id
       * </pre>
       *
       * <code>int64 taskid = 1;</code>
       * @param value The taskid to set.
       * @return This builder for chaining.
       */
      public Builder setTaskid(long value) {
        
        taskid_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 任务id
       * </pre>
       *
       * <code>int64 taskid = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearTaskid() {
        
        taskid_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object action_ = "";
      /**
       * <pre>
       * 指令名
       * </pre>
       *
       * <code>string action = 2;</code>
       * @return The action.
       */
      public java.lang.String getAction() {
        java.lang.Object ref = action_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          action_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 指令名
       * </pre>
       *
       * <code>string action = 2;</code>
       * @return The bytes for action.
       */
      public com.google.protobuf.ByteString
          getActionBytes() {
        java.lang.Object ref = action_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          action_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 指令名
       * </pre>
       *
       * <code>string action = 2;</code>
       * @param value The action to set.
       * @return This builder for chaining.
       */
      public Builder setAction(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        action_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 指令名
       * </pre>
       *
       * <code>string action = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearAction() {
        
        action_ = getDefaultInstance().getAction();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 指令名
       * </pre>
       *
       * <code>string action = 2;</code>
       * @param value The bytes for action to set.
       * @return This builder for chaining.
       */
      public Builder setActionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        action_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object params_ = "";
      /**
       * <pre>
       * 指令参数json字符串
       * </pre>
       *
       * <code>string params = 3;</code>
       * @return The params.
       */
      public java.lang.String getParams() {
        java.lang.Object ref = params_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          params_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 指令参数json字符串
       * </pre>
       *
       * <code>string params = 3;</code>
       * @return The bytes for params.
       */
      public com.google.protobuf.ByteString
          getParamsBytes() {
        java.lang.Object ref = params_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          params_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 指令参数json字符串
       * </pre>
       *
       * <code>string params = 3;</code>
       * @param value The params to set.
       * @return This builder for chaining.
       */
      public Builder setParams(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        params_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 指令参数json字符串
       * </pre>
       *
       * <code>string params = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearParams() {
        
        params_ = getDefaultInstance().getParams();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 指令参数json字符串
       * </pre>
       *
       * <code>string params = 3;</code>
       * @param value The bytes for params to set.
       * @return This builder for chaining.
       */
      public Builder setParamsBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        params_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:bilibili.broadcast.v2.LaserEventResp)
    }

    // @@protoc_insertion_point(class_scope:bilibili.broadcast.v2.LaserEventResp)
    private static final bilibili.broadcast.v2.LaserOuterClass.LaserEventResp DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new bilibili.broadcast.v2.LaserOuterClass.LaserEventResp();
    }

    public static bilibili.broadcast.v2.LaserOuterClass.LaserEventResp getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<LaserEventResp>
        PARSER = new com.google.protobuf.AbstractParser<LaserEventResp>() {
      @java.lang.Override
      public LaserEventResp parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<LaserEventResp> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<LaserEventResp> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public bilibili.broadcast.v2.LaserOuterClass.LaserEventResp getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bilibili_broadcast_v2_LaserEventResp_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_bilibili_broadcast_v2_LaserEventResp_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n!bilibili/broadcast/v2/laser.proto\022\025bil" +
      "ibili.broadcast.v2\032\033google/protobuf/empt" +
      "y.proto\"@\n\016LaserEventResp\022\016\n\006taskid\030\001 \001(" +
      "\003\022\016\n\006action\030\002 \001(\t\022\016\n\006params\030\003 \001(\t2V\n\005Las" +
      "er\022M\n\nWatchEvent\022\026.google.protobuf.Empty" +
      "\032%.bilibili.broadcast.v2.LaserEventResp0" +
      "\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.EmptyProto.getDescriptor(),
        });
    internal_static_bilibili_broadcast_v2_LaserEventResp_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_bilibili_broadcast_v2_LaserEventResp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_bilibili_broadcast_v2_LaserEventResp_descriptor,
        new java.lang.String[] { "Taskid", "Action", "Params", });
    com.google.protobuf.EmptyProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
