// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bilibili/app/show/gateway/v1/service.proto

package bilibili.app.show.gateway.v1;

public final class Service {
  private Service() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface GetActProgressReqOrBuilder extends
      // @@protoc_insertion_point(interface_extends:bilibili.app.show.gateway.v1.GetActProgressReq)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * Native页id
     * </pre>
     *
     * <code>int64 pageID = 1;</code>
     * @return The pageID.
     */
    long getPageID();

    /**
     * <pre>
     * 用户mid
     * </pre>
     *
     * <code>int64 mid = 2;</code>
     * @return The mid.
     */
    long getMid();
  }
  /**
   * <pre>
   * 获取Native页进度数据-请求
   * </pre>
   *
   * Protobuf type {@code bilibili.app.show.gateway.v1.GetActProgressReq}
   */
  public static final class GetActProgressReq extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:bilibili.app.show.gateway.v1.GetActProgressReq)
      GetActProgressReqOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use GetActProgressReq.newBuilder() to construct.
    private GetActProgressReq(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private GetActProgressReq() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new GetActProgressReq();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return bilibili.app.show.gateway.v1.Service.internal_static_bilibili_app_show_gateway_v1_GetActProgressReq_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return bilibili.app.show.gateway.v1.Service.internal_static_bilibili_app_show_gateway_v1_GetActProgressReq_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              bilibili.app.show.gateway.v1.Service.GetActProgressReq.class, bilibili.app.show.gateway.v1.Service.GetActProgressReq.Builder.class);
    }

    public static final int PAGEID_FIELD_NUMBER = 1;
    private long pageID_;
    /**
     * <pre>
     * Native页id
     * </pre>
     *
     * <code>int64 pageID = 1;</code>
     * @return The pageID.
     */
    @java.lang.Override
    public long getPageID() {
      return pageID_;
    }

    public static final int MID_FIELD_NUMBER = 2;
    private long mid_;
    /**
     * <pre>
     * 用户mid
     * </pre>
     *
     * <code>int64 mid = 2;</code>
     * @return The mid.
     */
    @java.lang.Override
    public long getMid() {
      return mid_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (pageID_ != 0L) {
        output.writeInt64(1, pageID_);
      }
      if (mid_ != 0L) {
        output.writeInt64(2, mid_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (pageID_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, pageID_);
      }
      if (mid_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, mid_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof bilibili.app.show.gateway.v1.Service.GetActProgressReq)) {
        return super.equals(obj);
      }
      bilibili.app.show.gateway.v1.Service.GetActProgressReq other = (bilibili.app.show.gateway.v1.Service.GetActProgressReq) obj;

      if (getPageID()
          != other.getPageID()) return false;
      if (getMid()
          != other.getMid()) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + PAGEID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getPageID());
      hash = (37 * hash) + MID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getMid());
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static bilibili.app.show.gateway.v1.Service.GetActProgressReq parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static bilibili.app.show.gateway.v1.Service.GetActProgressReq parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static bilibili.app.show.gateway.v1.Service.GetActProgressReq parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static bilibili.app.show.gateway.v1.Service.GetActProgressReq parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static bilibili.app.show.gateway.v1.Service.GetActProgressReq parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static bilibili.app.show.gateway.v1.Service.GetActProgressReq parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static bilibili.app.show.gateway.v1.Service.GetActProgressReq parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static bilibili.app.show.gateway.v1.Service.GetActProgressReq parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static bilibili.app.show.gateway.v1.Service.GetActProgressReq parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static bilibili.app.show.gateway.v1.Service.GetActProgressReq parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static bilibili.app.show.gateway.v1.Service.GetActProgressReq parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static bilibili.app.show.gateway.v1.Service.GetActProgressReq parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(bilibili.app.show.gateway.v1.Service.GetActProgressReq prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * 获取Native页进度数据-请求
     * </pre>
     *
     * Protobuf type {@code bilibili.app.show.gateway.v1.GetActProgressReq}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:bilibili.app.show.gateway.v1.GetActProgressReq)
        bilibili.app.show.gateway.v1.Service.GetActProgressReqOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return bilibili.app.show.gateway.v1.Service.internal_static_bilibili_app_show_gateway_v1_GetActProgressReq_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return bilibili.app.show.gateway.v1.Service.internal_static_bilibili_app_show_gateway_v1_GetActProgressReq_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                bilibili.app.show.gateway.v1.Service.GetActProgressReq.class, bilibili.app.show.gateway.v1.Service.GetActProgressReq.Builder.class);
      }

      // Construct using bilibili.app.show.gateway.v1.Service.GetActProgressReq.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        pageID_ = 0L;

        mid_ = 0L;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return bilibili.app.show.gateway.v1.Service.internal_static_bilibili_app_show_gateway_v1_GetActProgressReq_descriptor;
      }

      @java.lang.Override
      public bilibili.app.show.gateway.v1.Service.GetActProgressReq getDefaultInstanceForType() {
        return bilibili.app.show.gateway.v1.Service.GetActProgressReq.getDefaultInstance();
      }

      @java.lang.Override
      public bilibili.app.show.gateway.v1.Service.GetActProgressReq build() {
        bilibili.app.show.gateway.v1.Service.GetActProgressReq result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public bilibili.app.show.gateway.v1.Service.GetActProgressReq buildPartial() {
        bilibili.app.show.gateway.v1.Service.GetActProgressReq result = new bilibili.app.show.gateway.v1.Service.GetActProgressReq(this);
        result.pageID_ = pageID_;
        result.mid_ = mid_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof bilibili.app.show.gateway.v1.Service.GetActProgressReq) {
          return mergeFrom((bilibili.app.show.gateway.v1.Service.GetActProgressReq)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(bilibili.app.show.gateway.v1.Service.GetActProgressReq other) {
        if (other == bilibili.app.show.gateway.v1.Service.GetActProgressReq.getDefaultInstance()) return this;
        if (other.getPageID() != 0L) {
          setPageID(other.getPageID());
        }
        if (other.getMid() != 0L) {
          setMid(other.getMid());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                pageID_ = input.readInt64();

                break;
              } // case 8
              case 16: {
                mid_ = input.readInt64();

                break;
              } // case 16
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }

      private long pageID_ ;
      /**
       * <pre>
       * Native页id
       * </pre>
       *
       * <code>int64 pageID = 1;</code>
       * @return The pageID.
       */
      @java.lang.Override
      public long getPageID() {
        return pageID_;
      }
      /**
       * <pre>
       * Native页id
       * </pre>
       *
       * <code>int64 pageID = 1;</code>
       * @param value The pageID to set.
       * @return This builder for chaining.
       */
      public Builder setPageID(long value) {
        
        pageID_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Native页id
       * </pre>
       *
       * <code>int64 pageID = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearPageID() {
        
        pageID_ = 0L;
        onChanged();
        return this;
      }

      private long mid_ ;
      /**
       * <pre>
       * 用户mid
       * </pre>
       *
       * <code>int64 mid = 2;</code>
       * @return The mid.
       */
      @java.lang.Override
      public long getMid() {
        return mid_;
      }
      /**
       * <pre>
       * 用户mid
       * </pre>
       *
       * <code>int64 mid = 2;</code>
       * @param value The mid to set.
       * @return This builder for chaining.
       */
      public Builder setMid(long value) {
        
        mid_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 用户mid
       * </pre>
       *
       * <code>int64 mid = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearMid() {
        
        mid_ = 0L;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:bilibili.app.show.gateway.v1.GetActProgressReq)
    }

    // @@protoc_insertion_point(class_scope:bilibili.app.show.gateway.v1.GetActProgressReq)
    private static final bilibili.app.show.gateway.v1.Service.GetActProgressReq DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new bilibili.app.show.gateway.v1.Service.GetActProgressReq();
    }

    public static bilibili.app.show.gateway.v1.Service.GetActProgressReq getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<GetActProgressReq>
        PARSER = new com.google.protobuf.AbstractParser<GetActProgressReq>() {
      @java.lang.Override
      public GetActProgressReq parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<GetActProgressReq> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<GetActProgressReq> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public bilibili.app.show.gateway.v1.Service.GetActProgressReq getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface GetActProgressReplyOrBuilder extends
      // @@protoc_insertion_point(interface_extends:bilibili.app.show.gateway.v1.GetActProgressReply)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 进度数据
     * </pre>
     *
     * <code>.bilibili.broadcast.message.main.NativePageEvent event = 1;</code>
     * @return Whether the event field is set.
     */
    boolean hasEvent();
    /**
     * <pre>
     * 进度数据
     * </pre>
     *
     * <code>.bilibili.broadcast.message.main.NativePageEvent event = 1;</code>
     * @return The event.
     */
    bilibili.broadcast.message.main.Native.NativePageEvent getEvent();
    /**
     * <pre>
     * 进度数据
     * </pre>
     *
     * <code>.bilibili.broadcast.message.main.NativePageEvent event = 1;</code>
     */
    bilibili.broadcast.message.main.Native.NativePageEventOrBuilder getEventOrBuilder();
  }
  /**
   * <pre>
   * 获取Native页进度数据-响应
   * </pre>
   *
   * Protobuf type {@code bilibili.app.show.gateway.v1.GetActProgressReply}
   */
  public static final class GetActProgressReply extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:bilibili.app.show.gateway.v1.GetActProgressReply)
      GetActProgressReplyOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use GetActProgressReply.newBuilder() to construct.
    private GetActProgressReply(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private GetActProgressReply() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new GetActProgressReply();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return bilibili.app.show.gateway.v1.Service.internal_static_bilibili_app_show_gateway_v1_GetActProgressReply_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return bilibili.app.show.gateway.v1.Service.internal_static_bilibili_app_show_gateway_v1_GetActProgressReply_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              bilibili.app.show.gateway.v1.Service.GetActProgressReply.class, bilibili.app.show.gateway.v1.Service.GetActProgressReply.Builder.class);
    }

    public static final int EVENT_FIELD_NUMBER = 1;
    private bilibili.broadcast.message.main.Native.NativePageEvent event_;
    /**
     * <pre>
     * 进度数据
     * </pre>
     *
     * <code>.bilibili.broadcast.message.main.NativePageEvent event = 1;</code>
     * @return Whether the event field is set.
     */
    @java.lang.Override
    public boolean hasEvent() {
      return event_ != null;
    }
    /**
     * <pre>
     * 进度数据
     * </pre>
     *
     * <code>.bilibili.broadcast.message.main.NativePageEvent event = 1;</code>
     * @return The event.
     */
    @java.lang.Override
    public bilibili.broadcast.message.main.Native.NativePageEvent getEvent() {
      return event_ == null ? bilibili.broadcast.message.main.Native.NativePageEvent.getDefaultInstance() : event_;
    }
    /**
     * <pre>
     * 进度数据
     * </pre>
     *
     * <code>.bilibili.broadcast.message.main.NativePageEvent event = 1;</code>
     */
    @java.lang.Override
    public bilibili.broadcast.message.main.Native.NativePageEventOrBuilder getEventOrBuilder() {
      return getEvent();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (event_ != null) {
        output.writeMessage(1, getEvent());
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (event_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getEvent());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof bilibili.app.show.gateway.v1.Service.GetActProgressReply)) {
        return super.equals(obj);
      }
      bilibili.app.show.gateway.v1.Service.GetActProgressReply other = (bilibili.app.show.gateway.v1.Service.GetActProgressReply) obj;

      if (hasEvent() != other.hasEvent()) return false;
      if (hasEvent()) {
        if (!getEvent()
            .equals(other.getEvent())) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasEvent()) {
        hash = (37 * hash) + EVENT_FIELD_NUMBER;
        hash = (53 * hash) + getEvent().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static bilibili.app.show.gateway.v1.Service.GetActProgressReply parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static bilibili.app.show.gateway.v1.Service.GetActProgressReply parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static bilibili.app.show.gateway.v1.Service.GetActProgressReply parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static bilibili.app.show.gateway.v1.Service.GetActProgressReply parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static bilibili.app.show.gateway.v1.Service.GetActProgressReply parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static bilibili.app.show.gateway.v1.Service.GetActProgressReply parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static bilibili.app.show.gateway.v1.Service.GetActProgressReply parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static bilibili.app.show.gateway.v1.Service.GetActProgressReply parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static bilibili.app.show.gateway.v1.Service.GetActProgressReply parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static bilibili.app.show.gateway.v1.Service.GetActProgressReply parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static bilibili.app.show.gateway.v1.Service.GetActProgressReply parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static bilibili.app.show.gateway.v1.Service.GetActProgressReply parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(bilibili.app.show.gateway.v1.Service.GetActProgressReply prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * 获取Native页进度数据-响应
     * </pre>
     *
     * Protobuf type {@code bilibili.app.show.gateway.v1.GetActProgressReply}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:bilibili.app.show.gateway.v1.GetActProgressReply)
        bilibili.app.show.gateway.v1.Service.GetActProgressReplyOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return bilibili.app.show.gateway.v1.Service.internal_static_bilibili_app_show_gateway_v1_GetActProgressReply_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return bilibili.app.show.gateway.v1.Service.internal_static_bilibili_app_show_gateway_v1_GetActProgressReply_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                bilibili.app.show.gateway.v1.Service.GetActProgressReply.class, bilibili.app.show.gateway.v1.Service.GetActProgressReply.Builder.class);
      }

      // Construct using bilibili.app.show.gateway.v1.Service.GetActProgressReply.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (eventBuilder_ == null) {
          event_ = null;
        } else {
          event_ = null;
          eventBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return bilibili.app.show.gateway.v1.Service.internal_static_bilibili_app_show_gateway_v1_GetActProgressReply_descriptor;
      }

      @java.lang.Override
      public bilibili.app.show.gateway.v1.Service.GetActProgressReply getDefaultInstanceForType() {
        return bilibili.app.show.gateway.v1.Service.GetActProgressReply.getDefaultInstance();
      }

      @java.lang.Override
      public bilibili.app.show.gateway.v1.Service.GetActProgressReply build() {
        bilibili.app.show.gateway.v1.Service.GetActProgressReply result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public bilibili.app.show.gateway.v1.Service.GetActProgressReply buildPartial() {
        bilibili.app.show.gateway.v1.Service.GetActProgressReply result = new bilibili.app.show.gateway.v1.Service.GetActProgressReply(this);
        if (eventBuilder_ == null) {
          result.event_ = event_;
        } else {
          result.event_ = eventBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof bilibili.app.show.gateway.v1.Service.GetActProgressReply) {
          return mergeFrom((bilibili.app.show.gateway.v1.Service.GetActProgressReply)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(bilibili.app.show.gateway.v1.Service.GetActProgressReply other) {
        if (other == bilibili.app.show.gateway.v1.Service.GetActProgressReply.getDefaultInstance()) return this;
        if (other.hasEvent()) {
          mergeEvent(other.getEvent());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                input.readMessage(
                    getEventFieldBuilder().getBuilder(),
                    extensionRegistry);

                break;
              } // case 10
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }

      private bilibili.broadcast.message.main.Native.NativePageEvent event_;
      private com.google.protobuf.SingleFieldBuilderV3<
          bilibili.broadcast.message.main.Native.NativePageEvent, bilibili.broadcast.message.main.Native.NativePageEvent.Builder, bilibili.broadcast.message.main.Native.NativePageEventOrBuilder> eventBuilder_;
      /**
       * <pre>
       * 进度数据
       * </pre>
       *
       * <code>.bilibili.broadcast.message.main.NativePageEvent event = 1;</code>
       * @return Whether the event field is set.
       */
      public boolean hasEvent() {
        return eventBuilder_ != null || event_ != null;
      }
      /**
       * <pre>
       * 进度数据
       * </pre>
       *
       * <code>.bilibili.broadcast.message.main.NativePageEvent event = 1;</code>
       * @return The event.
       */
      public bilibili.broadcast.message.main.Native.NativePageEvent getEvent() {
        if (eventBuilder_ == null) {
          return event_ == null ? bilibili.broadcast.message.main.Native.NativePageEvent.getDefaultInstance() : event_;
        } else {
          return eventBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       * 进度数据
       * </pre>
       *
       * <code>.bilibili.broadcast.message.main.NativePageEvent event = 1;</code>
       */
      public Builder setEvent(bilibili.broadcast.message.main.Native.NativePageEvent value) {
        if (eventBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          event_ = value;
          onChanged();
        } else {
          eventBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <pre>
       * 进度数据
       * </pre>
       *
       * <code>.bilibili.broadcast.message.main.NativePageEvent event = 1;</code>
       */
      public Builder setEvent(
          bilibili.broadcast.message.main.Native.NativePageEvent.Builder builderForValue) {
        if (eventBuilder_ == null) {
          event_ = builderForValue.build();
          onChanged();
        } else {
          eventBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <pre>
       * 进度数据
       * </pre>
       *
       * <code>.bilibili.broadcast.message.main.NativePageEvent event = 1;</code>
       */
      public Builder mergeEvent(bilibili.broadcast.message.main.Native.NativePageEvent value) {
        if (eventBuilder_ == null) {
          if (event_ != null) {
            event_ =
              bilibili.broadcast.message.main.Native.NativePageEvent.newBuilder(event_).mergeFrom(value).buildPartial();
          } else {
            event_ = value;
          }
          onChanged();
        } else {
          eventBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <pre>
       * 进度数据
       * </pre>
       *
       * <code>.bilibili.broadcast.message.main.NativePageEvent event = 1;</code>
       */
      public Builder clearEvent() {
        if (eventBuilder_ == null) {
          event_ = null;
          onChanged();
        } else {
          event_ = null;
          eventBuilder_ = null;
        }

        return this;
      }
      /**
       * <pre>
       * 进度数据
       * </pre>
       *
       * <code>.bilibili.broadcast.message.main.NativePageEvent event = 1;</code>
       */
      public bilibili.broadcast.message.main.Native.NativePageEvent.Builder getEventBuilder() {
        
        onChanged();
        return getEventFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       * 进度数据
       * </pre>
       *
       * <code>.bilibili.broadcast.message.main.NativePageEvent event = 1;</code>
       */
      public bilibili.broadcast.message.main.Native.NativePageEventOrBuilder getEventOrBuilder() {
        if (eventBuilder_ != null) {
          return eventBuilder_.getMessageOrBuilder();
        } else {
          return event_ == null ?
              bilibili.broadcast.message.main.Native.NativePageEvent.getDefaultInstance() : event_;
        }
      }
      /**
       * <pre>
       * 进度数据
       * </pre>
       *
       * <code>.bilibili.broadcast.message.main.NativePageEvent event = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          bilibili.broadcast.message.main.Native.NativePageEvent, bilibili.broadcast.message.main.Native.NativePageEvent.Builder, bilibili.broadcast.message.main.Native.NativePageEventOrBuilder> 
          getEventFieldBuilder() {
        if (eventBuilder_ == null) {
          eventBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              bilibili.broadcast.message.main.Native.NativePageEvent, bilibili.broadcast.message.main.Native.NativePageEvent.Builder, bilibili.broadcast.message.main.Native.NativePageEventOrBuilder>(
                  getEvent(),
                  getParentForChildren(),
                  isClean());
          event_ = null;
        }
        return eventBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:bilibili.app.show.gateway.v1.GetActProgressReply)
    }

    // @@protoc_insertion_point(class_scope:bilibili.app.show.gateway.v1.GetActProgressReply)
    private static final bilibili.app.show.gateway.v1.Service.GetActProgressReply DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new bilibili.app.show.gateway.v1.Service.GetActProgressReply();
    }

    public static bilibili.app.show.gateway.v1.Service.GetActProgressReply getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<GetActProgressReply>
        PARSER = new com.google.protobuf.AbstractParser<GetActProgressReply>() {
      @java.lang.Override
      public GetActProgressReply parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<GetActProgressReply> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<GetActProgressReply> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public bilibili.app.show.gateway.v1.Service.GetActProgressReply getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bilibili_app_show_gateway_v1_GetActProgressReq_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_bilibili_app_show_gateway_v1_GetActProgressReq_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bilibili_app_show_gateway_v1_GetActProgressReply_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_bilibili_app_show_gateway_v1_GetActProgressReply_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n*bilibili/app/show/gateway/v1/service.p" +
      "roto\022\034bilibili.app.show.gateway.v1\032,bili" +
      "bili/broadcast/message/main/native.proto" +
      "\"0\n\021GetActProgressReq\022\016\n\006pageID\030\001 \001(\003\022\013\n" +
      "\003mid\030\002 \001(\003\"V\n\023GetActProgressReply\022?\n\005eve" +
      "nt\030\001 \001(\01320.bilibili.broadcast.message.ma" +
      "in.NativePageEvent2\177\n\007AppShow\022t\n\016GetActP" +
      "rogress\022/.bilibili.app.show.gateway.v1.G" +
      "etActProgressReq\0321.bilibili.app.show.gat" +
      "eway.v1.GetActProgressReplyb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          bilibili.broadcast.message.main.Native.getDescriptor(),
        });
    internal_static_bilibili_app_show_gateway_v1_GetActProgressReq_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_bilibili_app_show_gateway_v1_GetActProgressReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_bilibili_app_show_gateway_v1_GetActProgressReq_descriptor,
        new java.lang.String[] { "PageID", "Mid", });
    internal_static_bilibili_app_show_gateway_v1_GetActProgressReply_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_bilibili_app_show_gateway_v1_GetActProgressReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_bilibili_app_show_gateway_v1_GetActProgressReply_descriptor,
        new java.lang.String[] { "Event", });
    bilibili.broadcast.message.main.Native.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
