// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bilibili/metadata/parabox/pararbox.proto

package bilibili.metadata.parabox;

public final class Pararbox {
  private Pararbox() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ExpOrBuilder extends
      // @@protoc_insertion_point(interface_extends:bilibili.metadata.parabox.Exp)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * </pre>
     *
     * <code>int64 id = 1;</code>
     * @return The id.
     */
    long getId();

    /**
     * <pre>
     * </pre>
     *
     * <code>int32 bucket = 2;</code>
     * @return The bucket.
     */
    int getBucket();
  }
  /**
   * <pre>
   * </pre>
   *
   * Protobuf type {@code bilibili.metadata.parabox.Exp}
   */
  public static final class Exp extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:bilibili.metadata.parabox.Exp)
      ExpOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Exp.newBuilder() to construct.
    private Exp(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Exp() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Exp();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return bilibili.metadata.parabox.Pararbox.internal_static_bilibili_metadata_parabox_Exp_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return bilibili.metadata.parabox.Pararbox.internal_static_bilibili_metadata_parabox_Exp_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              bilibili.metadata.parabox.Pararbox.Exp.class, bilibili.metadata.parabox.Pararbox.Exp.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private long id_;
    /**
     * <pre>
     * </pre>
     *
     * <code>int64 id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public long getId() {
      return id_;
    }

    public static final int BUCKET_FIELD_NUMBER = 2;
    private int bucket_;
    /**
     * <pre>
     * </pre>
     *
     * <code>int32 bucket = 2;</code>
     * @return The bucket.
     */
    @java.lang.Override
    public int getBucket() {
      return bucket_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0L) {
        output.writeInt64(1, id_);
      }
      if (bucket_ != 0) {
        output.writeInt32(2, bucket_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, id_);
      }
      if (bucket_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, bucket_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof bilibili.metadata.parabox.Pararbox.Exp)) {
        return super.equals(obj);
      }
      bilibili.metadata.parabox.Pararbox.Exp other = (bilibili.metadata.parabox.Pararbox.Exp) obj;

      if (getId()
          != other.getId()) return false;
      if (getBucket()
          != other.getBucket()) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getId());
      hash = (37 * hash) + BUCKET_FIELD_NUMBER;
      hash = (53 * hash) + getBucket();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static bilibili.metadata.parabox.Pararbox.Exp parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static bilibili.metadata.parabox.Pararbox.Exp parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static bilibili.metadata.parabox.Pararbox.Exp parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static bilibili.metadata.parabox.Pararbox.Exp parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static bilibili.metadata.parabox.Pararbox.Exp parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static bilibili.metadata.parabox.Pararbox.Exp parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static bilibili.metadata.parabox.Pararbox.Exp parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static bilibili.metadata.parabox.Pararbox.Exp parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static bilibili.metadata.parabox.Pararbox.Exp parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static bilibili.metadata.parabox.Pararbox.Exp parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static bilibili.metadata.parabox.Pararbox.Exp parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static bilibili.metadata.parabox.Pararbox.Exp parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(bilibili.metadata.parabox.Pararbox.Exp prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * </pre>
     *
     * Protobuf type {@code bilibili.metadata.parabox.Exp}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:bilibili.metadata.parabox.Exp)
        bilibili.metadata.parabox.Pararbox.ExpOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return bilibili.metadata.parabox.Pararbox.internal_static_bilibili_metadata_parabox_Exp_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return bilibili.metadata.parabox.Pararbox.internal_static_bilibili_metadata_parabox_Exp_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                bilibili.metadata.parabox.Pararbox.Exp.class, bilibili.metadata.parabox.Pararbox.Exp.Builder.class);
      }

      // Construct using bilibili.metadata.parabox.Pararbox.Exp.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        id_ = 0L;

        bucket_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return bilibili.metadata.parabox.Pararbox.internal_static_bilibili_metadata_parabox_Exp_descriptor;
      }

      @java.lang.Override
      public bilibili.metadata.parabox.Pararbox.Exp getDefaultInstanceForType() {
        return bilibili.metadata.parabox.Pararbox.Exp.getDefaultInstance();
      }

      @java.lang.Override
      public bilibili.metadata.parabox.Pararbox.Exp build() {
        bilibili.metadata.parabox.Pararbox.Exp result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public bilibili.metadata.parabox.Pararbox.Exp buildPartial() {
        bilibili.metadata.parabox.Pararbox.Exp result = new bilibili.metadata.parabox.Pararbox.Exp(this);
        result.id_ = id_;
        result.bucket_ = bucket_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof bilibili.metadata.parabox.Pararbox.Exp) {
          return mergeFrom((bilibili.metadata.parabox.Pararbox.Exp)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(bilibili.metadata.parabox.Pararbox.Exp other) {
        if (other == bilibili.metadata.parabox.Pararbox.Exp.getDefaultInstance()) return this;
        if (other.getId() != 0L) {
          setId(other.getId());
        }
        if (other.getBucket() != 0) {
          setBucket(other.getBucket());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                id_ = input.readInt64();

                break;
              } // case 8
              case 16: {
                bucket_ = input.readInt32();

                break;
              } // case 16
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }

      private long id_ ;
      /**
       * <pre>
       * </pre>
       *
       * <code>int64 id = 1;</code>
       * @return The id.
       */
      @java.lang.Override
      public long getId() {
        return id_;
      }
      /**
       * <pre>
       * </pre>
       *
       * <code>int64 id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(long value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * </pre>
       *
       * <code>int64 id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        
        id_ = 0L;
        onChanged();
        return this;
      }

      private int bucket_ ;
      /**
       * <pre>
       * </pre>
       *
       * <code>int32 bucket = 2;</code>
       * @return The bucket.
       */
      @java.lang.Override
      public int getBucket() {
        return bucket_;
      }
      /**
       * <pre>
       * </pre>
       *
       * <code>int32 bucket = 2;</code>
       * @param value The bucket to set.
       * @return This builder for chaining.
       */
      public Builder setBucket(int value) {
        
        bucket_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * </pre>
       *
       * <code>int32 bucket = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearBucket() {
        
        bucket_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:bilibili.metadata.parabox.Exp)
    }

    // @@protoc_insertion_point(class_scope:bilibili.metadata.parabox.Exp)
    private static final bilibili.metadata.parabox.Pararbox.Exp DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new bilibili.metadata.parabox.Pararbox.Exp();
    }

    public static bilibili.metadata.parabox.Pararbox.Exp getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Exp>
        PARSER = new com.google.protobuf.AbstractParser<Exp>() {
      @java.lang.Override
      public Exp parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Exp> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Exp> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public bilibili.metadata.parabox.Pararbox.Exp getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ExpsOrBuilder extends
      // @@protoc_insertion_point(interface_extends:bilibili.metadata.parabox.Exps)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * </pre>
     *
     * <code>repeated .bilibili.metadata.parabox.Exp exps = 1;</code>
     */
    java.util.List<bilibili.metadata.parabox.Pararbox.Exp> 
        getExpsList();
    /**
     * <pre>
     * </pre>
     *
     * <code>repeated .bilibili.metadata.parabox.Exp exps = 1;</code>
     */
    bilibili.metadata.parabox.Pararbox.Exp getExps(int index);
    /**
     * <pre>
     * </pre>
     *
     * <code>repeated .bilibili.metadata.parabox.Exp exps = 1;</code>
     */
    int getExpsCount();
    /**
     * <pre>
     * </pre>
     *
     * <code>repeated .bilibili.metadata.parabox.Exp exps = 1;</code>
     */
    java.util.List<? extends bilibili.metadata.parabox.Pararbox.ExpOrBuilder> 
        getExpsOrBuilderList();
    /**
     * <pre>
     * </pre>
     *
     * <code>repeated .bilibili.metadata.parabox.Exp exps = 1;</code>
     */
    bilibili.metadata.parabox.Pararbox.ExpOrBuilder getExpsOrBuilder(
        int index);
  }
  /**
   * <pre>
   * </pre>
   *
   * Protobuf type {@code bilibili.metadata.parabox.Exps}
   */
  public static final class Exps extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:bilibili.metadata.parabox.Exps)
      ExpsOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Exps.newBuilder() to construct.
    private Exps(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Exps() {
      exps_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Exps();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return bilibili.metadata.parabox.Pararbox.internal_static_bilibili_metadata_parabox_Exps_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return bilibili.metadata.parabox.Pararbox.internal_static_bilibili_metadata_parabox_Exps_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              bilibili.metadata.parabox.Pararbox.Exps.class, bilibili.metadata.parabox.Pararbox.Exps.Builder.class);
    }

    public static final int EXPS_FIELD_NUMBER = 1;
    private java.util.List<bilibili.metadata.parabox.Pararbox.Exp> exps_;
    /**
     * <pre>
     * </pre>
     *
     * <code>repeated .bilibili.metadata.parabox.Exp exps = 1;</code>
     */
    @java.lang.Override
    public java.util.List<bilibili.metadata.parabox.Pararbox.Exp> getExpsList() {
      return exps_;
    }
    /**
     * <pre>
     * </pre>
     *
     * <code>repeated .bilibili.metadata.parabox.Exp exps = 1;</code>
     */
    @java.lang.Override
    public java.util.List<? extends bilibili.metadata.parabox.Pararbox.ExpOrBuilder> 
        getExpsOrBuilderList() {
      return exps_;
    }
    /**
     * <pre>
     * </pre>
     *
     * <code>repeated .bilibili.metadata.parabox.Exp exps = 1;</code>
     */
    @java.lang.Override
    public int getExpsCount() {
      return exps_.size();
    }
    /**
     * <pre>
     * </pre>
     *
     * <code>repeated .bilibili.metadata.parabox.Exp exps = 1;</code>
     */
    @java.lang.Override
    public bilibili.metadata.parabox.Pararbox.Exp getExps(int index) {
      return exps_.get(index);
    }
    /**
     * <pre>
     * </pre>
     *
     * <code>repeated .bilibili.metadata.parabox.Exp exps = 1;</code>
     */
    @java.lang.Override
    public bilibili.metadata.parabox.Pararbox.ExpOrBuilder getExpsOrBuilder(
        int index) {
      return exps_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < exps_.size(); i++) {
        output.writeMessage(1, exps_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < exps_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, exps_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof bilibili.metadata.parabox.Pararbox.Exps)) {
        return super.equals(obj);
      }
      bilibili.metadata.parabox.Pararbox.Exps other = (bilibili.metadata.parabox.Pararbox.Exps) obj;

      if (!getExpsList()
          .equals(other.getExpsList())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getExpsCount() > 0) {
        hash = (37 * hash) + EXPS_FIELD_NUMBER;
        hash = (53 * hash) + getExpsList().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static bilibili.metadata.parabox.Pararbox.Exps parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static bilibili.metadata.parabox.Pararbox.Exps parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static bilibili.metadata.parabox.Pararbox.Exps parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static bilibili.metadata.parabox.Pararbox.Exps parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static bilibili.metadata.parabox.Pararbox.Exps parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static bilibili.metadata.parabox.Pararbox.Exps parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static bilibili.metadata.parabox.Pararbox.Exps parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static bilibili.metadata.parabox.Pararbox.Exps parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static bilibili.metadata.parabox.Pararbox.Exps parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static bilibili.metadata.parabox.Pararbox.Exps parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static bilibili.metadata.parabox.Pararbox.Exps parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static bilibili.metadata.parabox.Pararbox.Exps parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(bilibili.metadata.parabox.Pararbox.Exps prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * </pre>
     *
     * Protobuf type {@code bilibili.metadata.parabox.Exps}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:bilibili.metadata.parabox.Exps)
        bilibili.metadata.parabox.Pararbox.ExpsOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return bilibili.metadata.parabox.Pararbox.internal_static_bilibili_metadata_parabox_Exps_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return bilibili.metadata.parabox.Pararbox.internal_static_bilibili_metadata_parabox_Exps_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                bilibili.metadata.parabox.Pararbox.Exps.class, bilibili.metadata.parabox.Pararbox.Exps.Builder.class);
      }

      // Construct using bilibili.metadata.parabox.Pararbox.Exps.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (expsBuilder_ == null) {
          exps_ = java.util.Collections.emptyList();
        } else {
          exps_ = null;
          expsBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return bilibili.metadata.parabox.Pararbox.internal_static_bilibili_metadata_parabox_Exps_descriptor;
      }

      @java.lang.Override
      public bilibili.metadata.parabox.Pararbox.Exps getDefaultInstanceForType() {
        return bilibili.metadata.parabox.Pararbox.Exps.getDefaultInstance();
      }

      @java.lang.Override
      public bilibili.metadata.parabox.Pararbox.Exps build() {
        bilibili.metadata.parabox.Pararbox.Exps result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public bilibili.metadata.parabox.Pararbox.Exps buildPartial() {
        bilibili.metadata.parabox.Pararbox.Exps result = new bilibili.metadata.parabox.Pararbox.Exps(this);
        int from_bitField0_ = bitField0_;
        if (expsBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            exps_ = java.util.Collections.unmodifiableList(exps_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.exps_ = exps_;
        } else {
          result.exps_ = expsBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof bilibili.metadata.parabox.Pararbox.Exps) {
          return mergeFrom((bilibili.metadata.parabox.Pararbox.Exps)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(bilibili.metadata.parabox.Pararbox.Exps other) {
        if (other == bilibili.metadata.parabox.Pararbox.Exps.getDefaultInstance()) return this;
        if (expsBuilder_ == null) {
          if (!other.exps_.isEmpty()) {
            if (exps_.isEmpty()) {
              exps_ = other.exps_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureExpsIsMutable();
              exps_.addAll(other.exps_);
            }
            onChanged();
          }
        } else {
          if (!other.exps_.isEmpty()) {
            if (expsBuilder_.isEmpty()) {
              expsBuilder_.dispose();
              expsBuilder_ = null;
              exps_ = other.exps_;
              bitField0_ = (bitField0_ & ~0x00000001);
              expsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getExpsFieldBuilder() : null;
            } else {
              expsBuilder_.addAllMessages(other.exps_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                bilibili.metadata.parabox.Pararbox.Exp m =
                    input.readMessage(
                        bilibili.metadata.parabox.Pararbox.Exp.parser(),
                        extensionRegistry);
                if (expsBuilder_ == null) {
                  ensureExpsIsMutable();
                  exps_.add(m);
                } else {
                  expsBuilder_.addMessage(m);
                }
                break;
              } // case 10
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.util.List<bilibili.metadata.parabox.Pararbox.Exp> exps_ =
        java.util.Collections.emptyList();
      private void ensureExpsIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          exps_ = new java.util.ArrayList<bilibili.metadata.parabox.Pararbox.Exp>(exps_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          bilibili.metadata.parabox.Pararbox.Exp, bilibili.metadata.parabox.Pararbox.Exp.Builder, bilibili.metadata.parabox.Pararbox.ExpOrBuilder> expsBuilder_;

      /**
       * <pre>
       * </pre>
       *
       * <code>repeated .bilibili.metadata.parabox.Exp exps = 1;</code>
       */
      public java.util.List<bilibili.metadata.parabox.Pararbox.Exp> getExpsList() {
        if (expsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(exps_);
        } else {
          return expsBuilder_.getMessageList();
        }
      }
      /**
       * <pre>
       * </pre>
       *
       * <code>repeated .bilibili.metadata.parabox.Exp exps = 1;</code>
       */
      public int getExpsCount() {
        if (expsBuilder_ == null) {
          return exps_.size();
        } else {
          return expsBuilder_.getCount();
        }
      }
      /**
       * <pre>
       * </pre>
       *
       * <code>repeated .bilibili.metadata.parabox.Exp exps = 1;</code>
       */
      public bilibili.metadata.parabox.Pararbox.Exp getExps(int index) {
        if (expsBuilder_ == null) {
          return exps_.get(index);
        } else {
          return expsBuilder_.getMessage(index);
        }
      }
      /**
       * <pre>
       * </pre>
       *
       * <code>repeated .bilibili.metadata.parabox.Exp exps = 1;</code>
       */
      public Builder setExps(
          int index, bilibili.metadata.parabox.Pararbox.Exp value) {
        if (expsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureExpsIsMutable();
          exps_.set(index, value);
          onChanged();
        } else {
          expsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       * </pre>
       *
       * <code>repeated .bilibili.metadata.parabox.Exp exps = 1;</code>
       */
      public Builder setExps(
          int index, bilibili.metadata.parabox.Pararbox.Exp.Builder builderForValue) {
        if (expsBuilder_ == null) {
          ensureExpsIsMutable();
          exps_.set(index, builderForValue.build());
          onChanged();
        } else {
          expsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * </pre>
       *
       * <code>repeated .bilibili.metadata.parabox.Exp exps = 1;</code>
       */
      public Builder addExps(bilibili.metadata.parabox.Pararbox.Exp value) {
        if (expsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureExpsIsMutable();
          exps_.add(value);
          onChanged();
        } else {
          expsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <pre>
       * </pre>
       *
       * <code>repeated .bilibili.metadata.parabox.Exp exps = 1;</code>
       */
      public Builder addExps(
          int index, bilibili.metadata.parabox.Pararbox.Exp value) {
        if (expsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureExpsIsMutable();
          exps_.add(index, value);
          onChanged();
        } else {
          expsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       * </pre>
       *
       * <code>repeated .bilibili.metadata.parabox.Exp exps = 1;</code>
       */
      public Builder addExps(
          bilibili.metadata.parabox.Pararbox.Exp.Builder builderForValue) {
        if (expsBuilder_ == null) {
          ensureExpsIsMutable();
          exps_.add(builderForValue.build());
          onChanged();
        } else {
          expsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * </pre>
       *
       * <code>repeated .bilibili.metadata.parabox.Exp exps = 1;</code>
       */
      public Builder addExps(
          int index, bilibili.metadata.parabox.Pararbox.Exp.Builder builderForValue) {
        if (expsBuilder_ == null) {
          ensureExpsIsMutable();
          exps_.add(index, builderForValue.build());
          onChanged();
        } else {
          expsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * </pre>
       *
       * <code>repeated .bilibili.metadata.parabox.Exp exps = 1;</code>
       */
      public Builder addAllExps(
          java.lang.Iterable<? extends bilibili.metadata.parabox.Pararbox.Exp> values) {
        if (expsBuilder_ == null) {
          ensureExpsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, exps_);
          onChanged();
        } else {
          expsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <pre>
       * </pre>
       *
       * <code>repeated .bilibili.metadata.parabox.Exp exps = 1;</code>
       */
      public Builder clearExps() {
        if (expsBuilder_ == null) {
          exps_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          expsBuilder_.clear();
        }
        return this;
      }
      /**
       * <pre>
       * </pre>
       *
       * <code>repeated .bilibili.metadata.parabox.Exp exps = 1;</code>
       */
      public Builder removeExps(int index) {
        if (expsBuilder_ == null) {
          ensureExpsIsMutable();
          exps_.remove(index);
          onChanged();
        } else {
          expsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <pre>
       * </pre>
       *
       * <code>repeated .bilibili.metadata.parabox.Exp exps = 1;</code>
       */
      public bilibili.metadata.parabox.Pararbox.Exp.Builder getExpsBuilder(
          int index) {
        return getExpsFieldBuilder().getBuilder(index);
      }
      /**
       * <pre>
       * </pre>
       *
       * <code>repeated .bilibili.metadata.parabox.Exp exps = 1;</code>
       */
      public bilibili.metadata.parabox.Pararbox.ExpOrBuilder getExpsOrBuilder(
          int index) {
        if (expsBuilder_ == null) {
          return exps_.get(index);  } else {
          return expsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <pre>
       * </pre>
       *
       * <code>repeated .bilibili.metadata.parabox.Exp exps = 1;</code>
       */
      public java.util.List<? extends bilibili.metadata.parabox.Pararbox.ExpOrBuilder> 
           getExpsOrBuilderList() {
        if (expsBuilder_ != null) {
          return expsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(exps_);
        }
      }
      /**
       * <pre>
       * </pre>
       *
       * <code>repeated .bilibili.metadata.parabox.Exp exps = 1;</code>
       */
      public bilibili.metadata.parabox.Pararbox.Exp.Builder addExpsBuilder() {
        return getExpsFieldBuilder().addBuilder(
            bilibili.metadata.parabox.Pararbox.Exp.getDefaultInstance());
      }
      /**
       * <pre>
       * </pre>
       *
       * <code>repeated .bilibili.metadata.parabox.Exp exps = 1;</code>
       */
      public bilibili.metadata.parabox.Pararbox.Exp.Builder addExpsBuilder(
          int index) {
        return getExpsFieldBuilder().addBuilder(
            index, bilibili.metadata.parabox.Pararbox.Exp.getDefaultInstance());
      }
      /**
       * <pre>
       * </pre>
       *
       * <code>repeated .bilibili.metadata.parabox.Exp exps = 1;</code>
       */
      public java.util.List<bilibili.metadata.parabox.Pararbox.Exp.Builder> 
           getExpsBuilderList() {
        return getExpsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          bilibili.metadata.parabox.Pararbox.Exp, bilibili.metadata.parabox.Pararbox.Exp.Builder, bilibili.metadata.parabox.Pararbox.ExpOrBuilder> 
          getExpsFieldBuilder() {
        if (expsBuilder_ == null) {
          expsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              bilibili.metadata.parabox.Pararbox.Exp, bilibili.metadata.parabox.Pararbox.Exp.Builder, bilibili.metadata.parabox.Pararbox.ExpOrBuilder>(
                  exps_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          exps_ = null;
        }
        return expsBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:bilibili.metadata.parabox.Exps)
    }

    // @@protoc_insertion_point(class_scope:bilibili.metadata.parabox.Exps)
    private static final bilibili.metadata.parabox.Pararbox.Exps DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new bilibili.metadata.parabox.Pararbox.Exps();
    }

    public static bilibili.metadata.parabox.Pararbox.Exps getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Exps>
        PARSER = new com.google.protobuf.AbstractParser<Exps>() {
      @java.lang.Override
      public Exps parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Exps> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Exps> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public bilibili.metadata.parabox.Pararbox.Exps getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bilibili_metadata_parabox_Exp_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_bilibili_metadata_parabox_Exp_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bilibili_metadata_parabox_Exps_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_bilibili_metadata_parabox_Exps_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n(bilibili/metadata/parabox/pararbox.pro" +
      "to\022\031bilibili.metadata.parabox\"!\n\003Exp\022\n\n\002" +
      "id\030\001 \001(\003\022\016\n\006bucket\030\002 \001(\005\"4\n\004Exps\022,\n\004exps" +
      "\030\001 \003(\0132\036.bilibili.metadata.parabox.Expb\006" +
      "proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_bilibili_metadata_parabox_Exp_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_bilibili_metadata_parabox_Exp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_bilibili_metadata_parabox_Exp_descriptor,
        new java.lang.String[] { "Id", "Bucket", });
    internal_static_bilibili_metadata_parabox_Exps_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_bilibili_metadata_parabox_Exps_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_bilibili_metadata_parabox_Exps_descriptor,
        new java.lang.String[] { "Exps", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
