// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pgc/biz/room.proto

package pgc.biz;

public final class Room {
  private Room() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface RoomProtoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:pgc.biz.RoomProto)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * </pre>
     *
     * <code>repeated string room_id = 1;</code>
     * @return A list containing the roomId.
     */
    java.util.List<java.lang.String>
        getRoomIdList();
    /**
     * <pre>
     * </pre>
     *
     * <code>repeated string room_id = 1;</code>
     * @return The count of roomId.
     */
    int getRoomIdCount();
    /**
     * <pre>
     * </pre>
     *
     * <code>repeated string room_id = 1;</code>
     * @param index The index of the element to return.
     * @return The roomId at the given index.
     */
    java.lang.String getRoomId(int index);
    /**
     * <pre>
     * </pre>
     *
     * <code>repeated string room_id = 1;</code>
     * @param index The index of the value to return.
     * @return The bytes of the roomId at the given index.
     */
    com.google.protobuf.ByteString
        getRoomIdBytes(int index);
  }
  /**
   * <pre>
   * </pre>
   *
   * Protobuf type {@code pgc.biz.RoomProto}
   */
  public static final class RoomProto extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:pgc.biz.RoomProto)
      RoomProtoOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use RoomProto.newBuilder() to construct.
    private RoomProto(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private RoomProto() {
      roomId_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new RoomProto();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return pgc.biz.Room.internal_static_pgc_biz_RoomProto_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return pgc.biz.Room.internal_static_pgc_biz_RoomProto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              pgc.biz.Room.RoomProto.class, pgc.biz.Room.RoomProto.Builder.class);
    }

    public static final int ROOM_ID_FIELD_NUMBER = 1;
    private com.google.protobuf.LazyStringList roomId_;
    /**
     * <pre>
     * </pre>
     *
     * <code>repeated string room_id = 1;</code>
     * @return A list containing the roomId.
     */
    public com.google.protobuf.ProtocolStringList
        getRoomIdList() {
      return roomId_;
    }
    /**
     * <pre>
     * </pre>
     *
     * <code>repeated string room_id = 1;</code>
     * @return The count of roomId.
     */
    public int getRoomIdCount() {
      return roomId_.size();
    }
    /**
     * <pre>
     * </pre>
     *
     * <code>repeated string room_id = 1;</code>
     * @param index The index of the element to return.
     * @return The roomId at the given index.
     */
    public java.lang.String getRoomId(int index) {
      return roomId_.get(index);
    }
    /**
     * <pre>
     * </pre>
     *
     * <code>repeated string room_id = 1;</code>
     * @param index The index of the value to return.
     * @return The bytes of the roomId at the given index.
     */
    public com.google.protobuf.ByteString
        getRoomIdBytes(int index) {
      return roomId_.getByteString(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < roomId_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, roomId_.getRaw(i));
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      {
        int dataSize = 0;
        for (int i = 0; i < roomId_.size(); i++) {
          dataSize += computeStringSizeNoTag(roomId_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getRoomIdList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof pgc.biz.Room.RoomProto)) {
        return super.equals(obj);
      }
      pgc.biz.Room.RoomProto other = (pgc.biz.Room.RoomProto) obj;

      if (!getRoomIdList()
          .equals(other.getRoomIdList())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getRoomIdCount() > 0) {
        hash = (37 * hash) + ROOM_ID_FIELD_NUMBER;
        hash = (53 * hash) + getRoomIdList().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static pgc.biz.Room.RoomProto parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pgc.biz.Room.RoomProto parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pgc.biz.Room.RoomProto parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pgc.biz.Room.RoomProto parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pgc.biz.Room.RoomProto parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pgc.biz.Room.RoomProto parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pgc.biz.Room.RoomProto parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static pgc.biz.Room.RoomProto parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static pgc.biz.Room.RoomProto parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static pgc.biz.Room.RoomProto parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static pgc.biz.Room.RoomProto parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static pgc.biz.Room.RoomProto parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(pgc.biz.Room.RoomProto prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * </pre>
     *
     * Protobuf type {@code pgc.biz.RoomProto}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:pgc.biz.RoomProto)
        pgc.biz.Room.RoomProtoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return pgc.biz.Room.internal_static_pgc_biz_RoomProto_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return pgc.biz.Room.internal_static_pgc_biz_RoomProto_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                pgc.biz.Room.RoomProto.class, pgc.biz.Room.RoomProto.Builder.class);
      }

      // Construct using pgc.biz.Room.RoomProto.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        roomId_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return pgc.biz.Room.internal_static_pgc_biz_RoomProto_descriptor;
      }

      @java.lang.Override
      public pgc.biz.Room.RoomProto getDefaultInstanceForType() {
        return pgc.biz.Room.RoomProto.getDefaultInstance();
      }

      @java.lang.Override
      public pgc.biz.Room.RoomProto build() {
        pgc.biz.Room.RoomProto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public pgc.biz.Room.RoomProto buildPartial() {
        pgc.biz.Room.RoomProto result = new pgc.biz.Room.RoomProto(this);
        int from_bitField0_ = bitField0_;
        if (((bitField0_ & 0x00000001) != 0)) {
          roomId_ = roomId_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.roomId_ = roomId_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof pgc.biz.Room.RoomProto) {
          return mergeFrom((pgc.biz.Room.RoomProto)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(pgc.biz.Room.RoomProto other) {
        if (other == pgc.biz.Room.RoomProto.getDefaultInstance()) return this;
        if (!other.roomId_.isEmpty()) {
          if (roomId_.isEmpty()) {
            roomId_ = other.roomId_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureRoomIdIsMutable();
            roomId_.addAll(other.roomId_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                java.lang.String s = input.readStringRequireUtf8();
                ensureRoomIdIsMutable();
                roomId_.add(s);
                break;
              } // case 10
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.LazyStringList roomId_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureRoomIdIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          roomId_ = new com.google.protobuf.LazyStringArrayList(roomId_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <pre>
       * </pre>
       *
       * <code>repeated string room_id = 1;</code>
       * @return A list containing the roomId.
       */
      public com.google.protobuf.ProtocolStringList
          getRoomIdList() {
        return roomId_.getUnmodifiableView();
      }
      /**
       * <pre>
       * </pre>
       *
       * <code>repeated string room_id = 1;</code>
       * @return The count of roomId.
       */
      public int getRoomIdCount() {
        return roomId_.size();
      }
      /**
       * <pre>
       * </pre>
       *
       * <code>repeated string room_id = 1;</code>
       * @param index The index of the element to return.
       * @return The roomId at the given index.
       */
      public java.lang.String getRoomId(int index) {
        return roomId_.get(index);
      }
      /**
       * <pre>
       * </pre>
       *
       * <code>repeated string room_id = 1;</code>
       * @param index The index of the value to return.
       * @return The bytes of the roomId at the given index.
       */
      public com.google.protobuf.ByteString
          getRoomIdBytes(int index) {
        return roomId_.getByteString(index);
      }
      /**
       * <pre>
       * </pre>
       *
       * <code>repeated string room_id = 1;</code>
       * @param index The index to set the value at.
       * @param value The roomId to set.
       * @return This builder for chaining.
       */
      public Builder setRoomId(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureRoomIdIsMutable();
        roomId_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * </pre>
       *
       * <code>repeated string room_id = 1;</code>
       * @param value The roomId to add.
       * @return This builder for chaining.
       */
      public Builder addRoomId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureRoomIdIsMutable();
        roomId_.add(value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * </pre>
       *
       * <code>repeated string room_id = 1;</code>
       * @param values The roomId to add.
       * @return This builder for chaining.
       */
      public Builder addAllRoomId(
          java.lang.Iterable<java.lang.String> values) {
        ensureRoomIdIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, roomId_);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * </pre>
       *
       * <code>repeated string room_id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearRoomId() {
        roomId_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * </pre>
       *
       * <code>repeated string room_id = 1;</code>
       * @param value The bytes of the roomId to add.
       * @return This builder for chaining.
       */
      public Builder addRoomIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensureRoomIdIsMutable();
        roomId_.add(value);
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:pgc.biz.RoomProto)
    }

    // @@protoc_insertion_point(class_scope:pgc.biz.RoomProto)
    private static final pgc.biz.Room.RoomProto DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new pgc.biz.Room.RoomProto();
    }

    public static pgc.biz.Room.RoomProto getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<RoomProto>
        PARSER = new com.google.protobuf.AbstractParser<RoomProto>() {
      @java.lang.Override
      public RoomProto parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<RoomProto> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<RoomProto> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public pgc.biz.Room.RoomProto getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pgc_biz_RoomProto_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pgc_biz_RoomProto_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022pgc/biz/room.proto\022\007pgc.biz\"\034\n\tRoomPro" +
      "to\022\017\n\007room_id\030\001 \003(\tb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_pgc_biz_RoomProto_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_pgc_biz_RoomProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pgc_biz_RoomProto_descriptor,
        new java.lang.String[] { "RoomId", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
