// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bilibili/broadcast/v1/test.proto

package bilibili.broadcast.v1;

public final class TestOuterClass {
  private TestOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface AddParamsOrBuilder extends
      // @@protoc_insertion_point(interface_extends:bilibili.broadcast.v1.AddParams)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * </pre>
     *
     * <code>int32 a = 1;</code>
     * @return The a.
     */
    int getA();

    /**
     * <pre>
     * </pre>
     *
     * <code>int32 b = 2;</code>
     * @return The b.
     */
    int getB();
  }
  /**
   * <pre>
   * </pre>
   *
   * Protobuf type {@code bilibili.broadcast.v1.AddParams}
   */
  public static final class AddParams extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:bilibili.broadcast.v1.AddParams)
      AddParamsOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use AddParams.newBuilder() to construct.
    private AddParams(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private AddParams() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new AddParams();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return bilibili.broadcast.v1.TestOuterClass.internal_static_bilibili_broadcast_v1_AddParams_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return bilibili.broadcast.v1.TestOuterClass.internal_static_bilibili_broadcast_v1_AddParams_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              bilibili.broadcast.v1.TestOuterClass.AddParams.class, bilibili.broadcast.v1.TestOuterClass.AddParams.Builder.class);
    }

    public static final int A_FIELD_NUMBER = 1;
    private int a_;
    /**
     * <pre>
     * </pre>
     *
     * <code>int32 a = 1;</code>
     * @return The a.
     */
    @java.lang.Override
    public int getA() {
      return a_;
    }

    public static final int B_FIELD_NUMBER = 2;
    private int b_;
    /**
     * <pre>
     * </pre>
     *
     * <code>int32 b = 2;</code>
     * @return The b.
     */
    @java.lang.Override
    public int getB() {
      return b_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (a_ != 0) {
        output.writeInt32(1, a_);
      }
      if (b_ != 0) {
        output.writeInt32(2, b_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (a_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, a_);
      }
      if (b_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, b_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof bilibili.broadcast.v1.TestOuterClass.AddParams)) {
        return super.equals(obj);
      }
      bilibili.broadcast.v1.TestOuterClass.AddParams other = (bilibili.broadcast.v1.TestOuterClass.AddParams) obj;

      if (getA()
          != other.getA()) return false;
      if (getB()
          != other.getB()) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + A_FIELD_NUMBER;
      hash = (53 * hash) + getA();
      hash = (37 * hash) + B_FIELD_NUMBER;
      hash = (53 * hash) + getB();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static bilibili.broadcast.v1.TestOuterClass.AddParams parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static bilibili.broadcast.v1.TestOuterClass.AddParams parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static bilibili.broadcast.v1.TestOuterClass.AddParams parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static bilibili.broadcast.v1.TestOuterClass.AddParams parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static bilibili.broadcast.v1.TestOuterClass.AddParams parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static bilibili.broadcast.v1.TestOuterClass.AddParams parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static bilibili.broadcast.v1.TestOuterClass.AddParams parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static bilibili.broadcast.v1.TestOuterClass.AddParams parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static bilibili.broadcast.v1.TestOuterClass.AddParams parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static bilibili.broadcast.v1.TestOuterClass.AddParams parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static bilibili.broadcast.v1.TestOuterClass.AddParams parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static bilibili.broadcast.v1.TestOuterClass.AddParams parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(bilibili.broadcast.v1.TestOuterClass.AddParams prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * </pre>
     *
     * Protobuf type {@code bilibili.broadcast.v1.AddParams}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:bilibili.broadcast.v1.AddParams)
        bilibili.broadcast.v1.TestOuterClass.AddParamsOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return bilibili.broadcast.v1.TestOuterClass.internal_static_bilibili_broadcast_v1_AddParams_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return bilibili.broadcast.v1.TestOuterClass.internal_static_bilibili_broadcast_v1_AddParams_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                bilibili.broadcast.v1.TestOuterClass.AddParams.class, bilibili.broadcast.v1.TestOuterClass.AddParams.Builder.class);
      }

      // Construct using bilibili.broadcast.v1.TestOuterClass.AddParams.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        a_ = 0;

        b_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return bilibili.broadcast.v1.TestOuterClass.internal_static_bilibili_broadcast_v1_AddParams_descriptor;
      }

      @java.lang.Override
      public bilibili.broadcast.v1.TestOuterClass.AddParams getDefaultInstanceForType() {
        return bilibili.broadcast.v1.TestOuterClass.AddParams.getDefaultInstance();
      }

      @java.lang.Override
      public bilibili.broadcast.v1.TestOuterClass.AddParams build() {
        bilibili.broadcast.v1.TestOuterClass.AddParams result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public bilibili.broadcast.v1.TestOuterClass.AddParams buildPartial() {
        bilibili.broadcast.v1.TestOuterClass.AddParams result = new bilibili.broadcast.v1.TestOuterClass.AddParams(this);
        result.a_ = a_;
        result.b_ = b_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof bilibili.broadcast.v1.TestOuterClass.AddParams) {
          return mergeFrom((bilibili.broadcast.v1.TestOuterClass.AddParams)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(bilibili.broadcast.v1.TestOuterClass.AddParams other) {
        if (other == bilibili.broadcast.v1.TestOuterClass.AddParams.getDefaultInstance()) return this;
        if (other.getA() != 0) {
          setA(other.getA());
        }
        if (other.getB() != 0) {
          setB(other.getB());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                a_ = input.readInt32();

                break;
              } // case 8
              case 16: {
                b_ = input.readInt32();

                break;
              } // case 16
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }

      private int a_ ;
      /**
       * <pre>
       * </pre>
       *
       * <code>int32 a = 1;</code>
       * @return The a.
       */
      @java.lang.Override
      public int getA() {
        return a_;
      }
      /**
       * <pre>
       * </pre>
       *
       * <code>int32 a = 1;</code>
       * @param value The a to set.
       * @return This builder for chaining.
       */
      public Builder setA(int value) {
        
        a_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * </pre>
       *
       * <code>int32 a = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearA() {
        
        a_ = 0;
        onChanged();
        return this;
      }

      private int b_ ;
      /**
       * <pre>
       * </pre>
       *
       * <code>int32 b = 2;</code>
       * @return The b.
       */
      @java.lang.Override
      public int getB() {
        return b_;
      }
      /**
       * <pre>
       * </pre>
       *
       * <code>int32 b = 2;</code>
       * @param value The b to set.
       * @return This builder for chaining.
       */
      public Builder setB(int value) {
        
        b_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * </pre>
       *
       * <code>int32 b = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearB() {
        
        b_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:bilibili.broadcast.v1.AddParams)
    }

    // @@protoc_insertion_point(class_scope:bilibili.broadcast.v1.AddParams)
    private static final bilibili.broadcast.v1.TestOuterClass.AddParams DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new bilibili.broadcast.v1.TestOuterClass.AddParams();
    }

    public static bilibili.broadcast.v1.TestOuterClass.AddParams getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<AddParams>
        PARSER = new com.google.protobuf.AbstractParser<AddParams>() {
      @java.lang.Override
      public AddParams parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<AddParams> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<AddParams> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public bilibili.broadcast.v1.TestOuterClass.AddParams getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface AddResultOrBuilder extends
      // @@protoc_insertion_point(interface_extends:bilibili.broadcast.v1.AddResult)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * </pre>
     *
     * <code>int32 r = 1;</code>
     * @return The r.
     */
    int getR();
  }
  /**
   * <pre>
   * </pre>
   *
   * Protobuf type {@code bilibili.broadcast.v1.AddResult}
   */
  public static final class AddResult extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:bilibili.broadcast.v1.AddResult)
      AddResultOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use AddResult.newBuilder() to construct.
    private AddResult(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private AddResult() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new AddResult();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return bilibili.broadcast.v1.TestOuterClass.internal_static_bilibili_broadcast_v1_AddResult_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return bilibili.broadcast.v1.TestOuterClass.internal_static_bilibili_broadcast_v1_AddResult_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              bilibili.broadcast.v1.TestOuterClass.AddResult.class, bilibili.broadcast.v1.TestOuterClass.AddResult.Builder.class);
    }

    public static final int R_FIELD_NUMBER = 1;
    private int r_;
    /**
     * <pre>
     * </pre>
     *
     * <code>int32 r = 1;</code>
     * @return The r.
     */
    @java.lang.Override
    public int getR() {
      return r_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (r_ != 0) {
        output.writeInt32(1, r_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (r_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, r_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof bilibili.broadcast.v1.TestOuterClass.AddResult)) {
        return super.equals(obj);
      }
      bilibili.broadcast.v1.TestOuterClass.AddResult other = (bilibili.broadcast.v1.TestOuterClass.AddResult) obj;

      if (getR()
          != other.getR()) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + R_FIELD_NUMBER;
      hash = (53 * hash) + getR();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static bilibili.broadcast.v1.TestOuterClass.AddResult parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static bilibili.broadcast.v1.TestOuterClass.AddResult parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static bilibili.broadcast.v1.TestOuterClass.AddResult parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static bilibili.broadcast.v1.TestOuterClass.AddResult parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static bilibili.broadcast.v1.TestOuterClass.AddResult parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static bilibili.broadcast.v1.TestOuterClass.AddResult parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static bilibili.broadcast.v1.TestOuterClass.AddResult parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static bilibili.broadcast.v1.TestOuterClass.AddResult parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static bilibili.broadcast.v1.TestOuterClass.AddResult parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static bilibili.broadcast.v1.TestOuterClass.AddResult parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static bilibili.broadcast.v1.TestOuterClass.AddResult parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static bilibili.broadcast.v1.TestOuterClass.AddResult parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(bilibili.broadcast.v1.TestOuterClass.AddResult prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * </pre>
     *
     * Protobuf type {@code bilibili.broadcast.v1.AddResult}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:bilibili.broadcast.v1.AddResult)
        bilibili.broadcast.v1.TestOuterClass.AddResultOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return bilibili.broadcast.v1.TestOuterClass.internal_static_bilibili_broadcast_v1_AddResult_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return bilibili.broadcast.v1.TestOuterClass.internal_static_bilibili_broadcast_v1_AddResult_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                bilibili.broadcast.v1.TestOuterClass.AddResult.class, bilibili.broadcast.v1.TestOuterClass.AddResult.Builder.class);
      }

      // Construct using bilibili.broadcast.v1.TestOuterClass.AddResult.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        r_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return bilibili.broadcast.v1.TestOuterClass.internal_static_bilibili_broadcast_v1_AddResult_descriptor;
      }

      @java.lang.Override
      public bilibili.broadcast.v1.TestOuterClass.AddResult getDefaultInstanceForType() {
        return bilibili.broadcast.v1.TestOuterClass.AddResult.getDefaultInstance();
      }

      @java.lang.Override
      public bilibili.broadcast.v1.TestOuterClass.AddResult build() {
        bilibili.broadcast.v1.TestOuterClass.AddResult result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public bilibili.broadcast.v1.TestOuterClass.AddResult buildPartial() {
        bilibili.broadcast.v1.TestOuterClass.AddResult result = new bilibili.broadcast.v1.TestOuterClass.AddResult(this);
        result.r_ = r_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof bilibili.broadcast.v1.TestOuterClass.AddResult) {
          return mergeFrom((bilibili.broadcast.v1.TestOuterClass.AddResult)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(bilibili.broadcast.v1.TestOuterClass.AddResult other) {
        if (other == bilibili.broadcast.v1.TestOuterClass.AddResult.getDefaultInstance()) return this;
        if (other.getR() != 0) {
          setR(other.getR());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                r_ = input.readInt32();

                break;
              } // case 8
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }

      private int r_ ;
      /**
       * <pre>
       * </pre>
       *
       * <code>int32 r = 1;</code>
       * @return The r.
       */
      @java.lang.Override
      public int getR() {
        return r_;
      }
      /**
       * <pre>
       * </pre>
       *
       * <code>int32 r = 1;</code>
       * @param value The r to set.
       * @return This builder for chaining.
       */
      public Builder setR(int value) {
        
        r_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * </pre>
       *
       * <code>int32 r = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearR() {
        
        r_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:bilibili.broadcast.v1.AddResult)
    }

    // @@protoc_insertion_point(class_scope:bilibili.broadcast.v1.AddResult)
    private static final bilibili.broadcast.v1.TestOuterClass.AddResult DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new bilibili.broadcast.v1.TestOuterClass.AddResult();
    }

    public static bilibili.broadcast.v1.TestOuterClass.AddResult getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<AddResult>
        PARSER = new com.google.protobuf.AbstractParser<AddResult>() {
      @java.lang.Override
      public AddResult parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<AddResult> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<AddResult> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public bilibili.broadcast.v1.TestOuterClass.AddResult getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface TestRespOrBuilder extends
      // @@protoc_insertion_point(interface_extends:bilibili.broadcast.v1.TestResp)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 任务id
     * </pre>
     *
     * <code>int64 taskid = 1;</code>
     * @return The taskid.
     */
    long getTaskid();

    /**
     * <pre>
     * 时间戳
     * </pre>
     *
     * <code>int64 timestamp = 2;</code>
     * @return The timestamp.
     */
    long getTimestamp();

    /**
     * <pre>
     * 消息
     * </pre>
     *
     * <code>string message = 3;</code>
     * @return The message.
     */
    java.lang.String getMessage();
    /**
     * <pre>
     * 消息
     * </pre>
     *
     * <code>string message = 3;</code>
     * @return The bytes for message.
     */
    com.google.protobuf.ByteString
        getMessageBytes();

    /**
     * <pre>
     * 扩展
     * </pre>
     *
     * <code>.google.protobuf.Any extra = 4;</code>
     * @return Whether the extra field is set.
     */
    boolean hasExtra();
    /**
     * <pre>
     * 扩展
     * </pre>
     *
     * <code>.google.protobuf.Any extra = 4;</code>
     * @return The extra.
     */
    com.google.protobuf.Any getExtra();
    /**
     * <pre>
     * 扩展
     * </pre>
     *
     * <code>.google.protobuf.Any extra = 4;</code>
     */
    com.google.protobuf.AnyOrBuilder getExtraOrBuilder();
  }
  /**
   * Protobuf type {@code bilibili.broadcast.v1.TestResp}
   */
  public static final class TestResp extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:bilibili.broadcast.v1.TestResp)
      TestRespOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use TestResp.newBuilder() to construct.
    private TestResp(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private TestResp() {
      message_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new TestResp();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return bilibili.broadcast.v1.TestOuterClass.internal_static_bilibili_broadcast_v1_TestResp_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return bilibili.broadcast.v1.TestOuterClass.internal_static_bilibili_broadcast_v1_TestResp_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              bilibili.broadcast.v1.TestOuterClass.TestResp.class, bilibili.broadcast.v1.TestOuterClass.TestResp.Builder.class);
    }

    public static final int TASKID_FIELD_NUMBER = 1;
    private long taskid_;
    /**
     * <pre>
     * 任务id
     * </pre>
     *
     * <code>int64 taskid = 1;</code>
     * @return The taskid.
     */
    @java.lang.Override
    public long getTaskid() {
      return taskid_;
    }

    public static final int TIMESTAMP_FIELD_NUMBER = 2;
    private long timestamp_;
    /**
     * <pre>
     * 时间戳
     * </pre>
     *
     * <code>int64 timestamp = 2;</code>
     * @return The timestamp.
     */
    @java.lang.Override
    public long getTimestamp() {
      return timestamp_;
    }

    public static final int MESSAGE_FIELD_NUMBER = 3;
    private volatile java.lang.Object message_;
    /**
     * <pre>
     * 消息
     * </pre>
     *
     * <code>string message = 3;</code>
     * @return The message.
     */
    @java.lang.Override
    public java.lang.String getMessage() {
      java.lang.Object ref = message_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        message_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 消息
     * </pre>
     *
     * <code>string message = 3;</code>
     * @return The bytes for message.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getMessageBytes() {
      java.lang.Object ref = message_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        message_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int EXTRA_FIELD_NUMBER = 4;
    private com.google.protobuf.Any extra_;
    /**
     * <pre>
     * 扩展
     * </pre>
     *
     * <code>.google.protobuf.Any extra = 4;</code>
     * @return Whether the extra field is set.
     */
    @java.lang.Override
    public boolean hasExtra() {
      return extra_ != null;
    }
    /**
     * <pre>
     * 扩展
     * </pre>
     *
     * <code>.google.protobuf.Any extra = 4;</code>
     * @return The extra.
     */
    @java.lang.Override
    public com.google.protobuf.Any getExtra() {
      return extra_ == null ? com.google.protobuf.Any.getDefaultInstance() : extra_;
    }
    /**
     * <pre>
     * 扩展
     * </pre>
     *
     * <code>.google.protobuf.Any extra = 4;</code>
     */
    @java.lang.Override
    public com.google.protobuf.AnyOrBuilder getExtraOrBuilder() {
      return getExtra();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (taskid_ != 0L) {
        output.writeInt64(1, taskid_);
      }
      if (timestamp_ != 0L) {
        output.writeInt64(2, timestamp_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(message_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, message_);
      }
      if (extra_ != null) {
        output.writeMessage(4, getExtra());
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (taskid_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, taskid_);
      }
      if (timestamp_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, timestamp_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(message_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, message_);
      }
      if (extra_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, getExtra());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof bilibili.broadcast.v1.TestOuterClass.TestResp)) {
        return super.equals(obj);
      }
      bilibili.broadcast.v1.TestOuterClass.TestResp other = (bilibili.broadcast.v1.TestOuterClass.TestResp) obj;

      if (getTaskid()
          != other.getTaskid()) return false;
      if (getTimestamp()
          != other.getTimestamp()) return false;
      if (!getMessage()
          .equals(other.getMessage())) return false;
      if (hasExtra() != other.hasExtra()) return false;
      if (hasExtra()) {
        if (!getExtra()
            .equals(other.getExtra())) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TASKID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTaskid());
      hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTimestamp());
      hash = (37 * hash) + MESSAGE_FIELD_NUMBER;
      hash = (53 * hash) + getMessage().hashCode();
      if (hasExtra()) {
        hash = (37 * hash) + EXTRA_FIELD_NUMBER;
        hash = (53 * hash) + getExtra().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static bilibili.broadcast.v1.TestOuterClass.TestResp parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static bilibili.broadcast.v1.TestOuterClass.TestResp parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static bilibili.broadcast.v1.TestOuterClass.TestResp parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static bilibili.broadcast.v1.TestOuterClass.TestResp parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static bilibili.broadcast.v1.TestOuterClass.TestResp parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static bilibili.broadcast.v1.TestOuterClass.TestResp parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static bilibili.broadcast.v1.TestOuterClass.TestResp parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static bilibili.broadcast.v1.TestOuterClass.TestResp parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static bilibili.broadcast.v1.TestOuterClass.TestResp parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static bilibili.broadcast.v1.TestOuterClass.TestResp parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static bilibili.broadcast.v1.TestOuterClass.TestResp parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static bilibili.broadcast.v1.TestOuterClass.TestResp parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(bilibili.broadcast.v1.TestOuterClass.TestResp prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code bilibili.broadcast.v1.TestResp}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:bilibili.broadcast.v1.TestResp)
        bilibili.broadcast.v1.TestOuterClass.TestRespOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return bilibili.broadcast.v1.TestOuterClass.internal_static_bilibili_broadcast_v1_TestResp_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return bilibili.broadcast.v1.TestOuterClass.internal_static_bilibili_broadcast_v1_TestResp_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                bilibili.broadcast.v1.TestOuterClass.TestResp.class, bilibili.broadcast.v1.TestOuterClass.TestResp.Builder.class);
      }

      // Construct using bilibili.broadcast.v1.TestOuterClass.TestResp.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        taskid_ = 0L;

        timestamp_ = 0L;

        message_ = "";

        if (extraBuilder_ == null) {
          extra_ = null;
        } else {
          extra_ = null;
          extraBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return bilibili.broadcast.v1.TestOuterClass.internal_static_bilibili_broadcast_v1_TestResp_descriptor;
      }

      @java.lang.Override
      public bilibili.broadcast.v1.TestOuterClass.TestResp getDefaultInstanceForType() {
        return bilibili.broadcast.v1.TestOuterClass.TestResp.getDefaultInstance();
      }

      @java.lang.Override
      public bilibili.broadcast.v1.TestOuterClass.TestResp build() {
        bilibili.broadcast.v1.TestOuterClass.TestResp result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public bilibili.broadcast.v1.TestOuterClass.TestResp buildPartial() {
        bilibili.broadcast.v1.TestOuterClass.TestResp result = new bilibili.broadcast.v1.TestOuterClass.TestResp(this);
        result.taskid_ = taskid_;
        result.timestamp_ = timestamp_;
        result.message_ = message_;
        if (extraBuilder_ == null) {
          result.extra_ = extra_;
        } else {
          result.extra_ = extraBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof bilibili.broadcast.v1.TestOuterClass.TestResp) {
          return mergeFrom((bilibili.broadcast.v1.TestOuterClass.TestResp)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(bilibili.broadcast.v1.TestOuterClass.TestResp other) {
        if (other == bilibili.broadcast.v1.TestOuterClass.TestResp.getDefaultInstance()) return this;
        if (other.getTaskid() != 0L) {
          setTaskid(other.getTaskid());
        }
        if (other.getTimestamp() != 0L) {
          setTimestamp(other.getTimestamp());
        }
        if (!other.getMessage().isEmpty()) {
          message_ = other.message_;
          onChanged();
        }
        if (other.hasExtra()) {
          mergeExtra(other.getExtra());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                taskid_ = input.readInt64();

                break;
              } // case 8
              case 16: {
                timestamp_ = input.readInt64();

                break;
              } // case 16
              case 26: {
                message_ = input.readStringRequireUtf8();

                break;
              } // case 26
              case 34: {
                input.readMessage(
                    getExtraFieldBuilder().getBuilder(),
                    extensionRegistry);

                break;
              } // case 34
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }

      private long taskid_ ;
      /**
       * <pre>
       * 任务id
       * </pre>
       *
       * <code>int64 taskid = 1;</code>
       * @return The taskid.
       */
      @java.lang.Override
      public long getTaskid() {
        return taskid_;
      }
      /**
       * <pre>
       * 任务id
       * </pre>
       *
       * <code>int64 taskid = 1;</code>
       * @param value The taskid to set.
       * @return This builder for chaining.
       */
      public Builder setTaskid(long value) {
        
        taskid_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 任务id
       * </pre>
       *
       * <code>int64 taskid = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearTaskid() {
        
        taskid_ = 0L;
        onChanged();
        return this;
      }

      private long timestamp_ ;
      /**
       * <pre>
       * 时间戳
       * </pre>
       *
       * <code>int64 timestamp = 2;</code>
       * @return The timestamp.
       */
      @java.lang.Override
      public long getTimestamp() {
        return timestamp_;
      }
      /**
       * <pre>
       * 时间戳
       * </pre>
       *
       * <code>int64 timestamp = 2;</code>
       * @param value The timestamp to set.
       * @return This builder for chaining.
       */
      public Builder setTimestamp(long value) {
        
        timestamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 时间戳
       * </pre>
       *
       * <code>int64 timestamp = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearTimestamp() {
        
        timestamp_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object message_ = "";
      /**
       * <pre>
       * 消息
       * </pre>
       *
       * <code>string message = 3;</code>
       * @return The message.
       */
      public java.lang.String getMessage() {
        java.lang.Object ref = message_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          message_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 消息
       * </pre>
       *
       * <code>string message = 3;</code>
       * @return The bytes for message.
       */
      public com.google.protobuf.ByteString
          getMessageBytes() {
        java.lang.Object ref = message_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          message_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 消息
       * </pre>
       *
       * <code>string message = 3;</code>
       * @param value The message to set.
       * @return This builder for chaining.
       */
      public Builder setMessage(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        message_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 消息
       * </pre>
       *
       * <code>string message = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearMessage() {
        
        message_ = getDefaultInstance().getMessage();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 消息
       * </pre>
       *
       * <code>string message = 3;</code>
       * @param value The bytes for message to set.
       * @return This builder for chaining.
       */
      public Builder setMessageBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        message_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.Any extra_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder> extraBuilder_;
      /**
       * <pre>
       * 扩展
       * </pre>
       *
       * <code>.google.protobuf.Any extra = 4;</code>
       * @return Whether the extra field is set.
       */
      public boolean hasExtra() {
        return extraBuilder_ != null || extra_ != null;
      }
      /**
       * <pre>
       * 扩展
       * </pre>
       *
       * <code>.google.protobuf.Any extra = 4;</code>
       * @return The extra.
       */
      public com.google.protobuf.Any getExtra() {
        if (extraBuilder_ == null) {
          return extra_ == null ? com.google.protobuf.Any.getDefaultInstance() : extra_;
        } else {
          return extraBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       * 扩展
       * </pre>
       *
       * <code>.google.protobuf.Any extra = 4;</code>
       */
      public Builder setExtra(com.google.protobuf.Any value) {
        if (extraBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          extra_ = value;
          onChanged();
        } else {
          extraBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <pre>
       * 扩展
       * </pre>
       *
       * <code>.google.protobuf.Any extra = 4;</code>
       */
      public Builder setExtra(
          com.google.protobuf.Any.Builder builderForValue) {
        if (extraBuilder_ == null) {
          extra_ = builderForValue.build();
          onChanged();
        } else {
          extraBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <pre>
       * 扩展
       * </pre>
       *
       * <code>.google.protobuf.Any extra = 4;</code>
       */
      public Builder mergeExtra(com.google.protobuf.Any value) {
        if (extraBuilder_ == null) {
          if (extra_ != null) {
            extra_ =
              com.google.protobuf.Any.newBuilder(extra_).mergeFrom(value).buildPartial();
          } else {
            extra_ = value;
          }
          onChanged();
        } else {
          extraBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <pre>
       * 扩展
       * </pre>
       *
       * <code>.google.protobuf.Any extra = 4;</code>
       */
      public Builder clearExtra() {
        if (extraBuilder_ == null) {
          extra_ = null;
          onChanged();
        } else {
          extra_ = null;
          extraBuilder_ = null;
        }

        return this;
      }
      /**
       * <pre>
       * 扩展
       * </pre>
       *
       * <code>.google.protobuf.Any extra = 4;</code>
       */
      public com.google.protobuf.Any.Builder getExtraBuilder() {
        
        onChanged();
        return getExtraFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       * 扩展
       * </pre>
       *
       * <code>.google.protobuf.Any extra = 4;</code>
       */
      public com.google.protobuf.AnyOrBuilder getExtraOrBuilder() {
        if (extraBuilder_ != null) {
          return extraBuilder_.getMessageOrBuilder();
        } else {
          return extra_ == null ?
              com.google.protobuf.Any.getDefaultInstance() : extra_;
        }
      }
      /**
       * <pre>
       * 扩展
       * </pre>
       *
       * <code>.google.protobuf.Any extra = 4;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder> 
          getExtraFieldBuilder() {
        if (extraBuilder_ == null) {
          extraBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder>(
                  getExtra(),
                  getParentForChildren(),
                  isClean());
          extra_ = null;
        }
        return extraBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:bilibili.broadcast.v1.TestResp)
    }

    // @@protoc_insertion_point(class_scope:bilibili.broadcast.v1.TestResp)
    private static final bilibili.broadcast.v1.TestOuterClass.TestResp DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new bilibili.broadcast.v1.TestOuterClass.TestResp();
    }

    public static bilibili.broadcast.v1.TestOuterClass.TestResp getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<TestResp>
        PARSER = new com.google.protobuf.AbstractParser<TestResp>() {
      @java.lang.Override
      public TestResp parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<TestResp> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<TestResp> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public bilibili.broadcast.v1.TestOuterClass.TestResp getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bilibili_broadcast_v1_AddParams_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_bilibili_broadcast_v1_AddParams_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bilibili_broadcast_v1_AddResult_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_bilibili_broadcast_v1_AddResult_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bilibili_broadcast_v1_TestResp_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_bilibili_broadcast_v1_TestResp_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n bilibili/broadcast/v1/test.proto\022\025bili" +
      "bili.broadcast.v1\032\031google/protobuf/any.p" +
      "roto\032\033google/protobuf/empty.proto\"!\n\tAdd" +
      "Params\022\t\n\001a\030\001 \001(\005\022\t\n\001b\030\002 \001(\005\"\026\n\tAddResul" +
      "t\022\t\n\001r\030\001 \001(\005\"c\n\010TestResp\022\016\n\006taskid\030\001 \001(\003" +
      "\022\021\n\ttimestamp\030\002 \001(\003\022\017\n\007message\030\003 \001(\t\022#\n\005" +
      "extra\030\004 \001(\0132\024.google.protobuf.Any2S\n\004Tes" +
      "t\022K\n\016WatchTestEvent\022\026.google.protobuf.Em" +
      "pty\032\037.bilibili.broadcast.v1.TestResp0\0012I" +
      "\n\005Test2\022@\n\004Test\022 .bilibili.broadcast.v1." +
      "AddParams\032\026.google.protobuf.Emptyb\006proto" +
      "3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.AnyProto.getDescriptor(),
          com.google.protobuf.EmptyProto.getDescriptor(),
        });
    internal_static_bilibili_broadcast_v1_AddParams_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_bilibili_broadcast_v1_AddParams_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_bilibili_broadcast_v1_AddParams_descriptor,
        new java.lang.String[] { "A", "B", });
    internal_static_bilibili_broadcast_v1_AddResult_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_bilibili_broadcast_v1_AddResult_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_bilibili_broadcast_v1_AddResult_descriptor,
        new java.lang.String[] { "R", });
    internal_static_bilibili_broadcast_v1_TestResp_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_bilibili_broadcast_v1_TestResp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_bilibili_broadcast_v1_TestResp_descriptor,
        new java.lang.String[] { "Taskid", "Timestamp", "Message", "Extra", });
    com.google.protobuf.AnyProto.getDescriptor();
    com.google.protobuf.EmptyProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
