// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bilibili/community/service/govern/v1/govern.proto

package bilibili.community.service.govern.v1;

public final class Govern {
  private Govern() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface QoeReportReqOrBuilder extends
      // @@protoc_insertion_point(interface_extends:bilibili.community.service.govern.v1.QoeReportReq)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * </pre>
     *
     * <code>int64 id = 1;</code>
     * @return The id.
     */
    long getId();

    /**
     * <pre>
     * </pre>
     *
     * <code>int64 scene = 2;</code>
     * @return The scene.
     */
    long getScene();

    /**
     * <pre>
     * </pre>
     *
     * <code>int32 type = 3;</code>
     * @return The type.
     */
    int getType();

    /**
     * <pre>
     * </pre>
     *
     * <code>bool cancel = 4;</code>
     * @return The cancel.
     */
    boolean getCancel();

    /**
     * <pre>
     * </pre>
     *
     * <code>string business_type = 5;</code>
     * @return The businessType.
     */
    java.lang.String getBusinessType();
    /**
     * <pre>
     * </pre>
     *
     * <code>string business_type = 5;</code>
     * @return The bytes for businessType.
     */
    com.google.protobuf.ByteString
        getBusinessTypeBytes();

    /**
     * <pre>
     * </pre>
     *
     * <code>int64 oid = 6;</code>
     * @return The oid.
     */
    long getOid();

    /**
     * <pre>
     * </pre>
     *
     * <code>.bilibili.community.service.govern.v1.QoeScoreResult score_result = 7;</code>
     * @return Whether the scoreResult field is set.
     */
    boolean hasScoreResult();
    /**
     * <pre>
     * </pre>
     *
     * <code>.bilibili.community.service.govern.v1.QoeScoreResult score_result = 7;</code>
     * @return The scoreResult.
     */
    bilibili.community.service.govern.v1.Govern.QoeScoreResult getScoreResult();
    /**
     * <pre>
     * </pre>
     *
     * <code>.bilibili.community.service.govern.v1.QoeScoreResult score_result = 7;</code>
     */
    bilibili.community.service.govern.v1.Govern.QoeScoreResultOrBuilder getScoreResultOrBuilder();

    /**
     * <pre>
     * </pre>
     *
     * <code>string business_data = 8;</code>
     * @return The businessData.
     */
    java.lang.String getBusinessData();
    /**
     * <pre>
     * </pre>
     *
     * <code>string business_data = 8;</code>
     * @return The bytes for businessData.
     */
    com.google.protobuf.ByteString
        getBusinessDataBytes();
  }
  /**
   * <pre>
   * </pre>
   *
   * Protobuf type {@code bilibili.community.service.govern.v1.QoeReportReq}
   */
  public static final class QoeReportReq extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:bilibili.community.service.govern.v1.QoeReportReq)
      QoeReportReqOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use QoeReportReq.newBuilder() to construct.
    private QoeReportReq(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private QoeReportReq() {
      businessType_ = "";
      businessData_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new QoeReportReq();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return bilibili.community.service.govern.v1.Govern.internal_static_bilibili_community_service_govern_v1_QoeReportReq_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return bilibili.community.service.govern.v1.Govern.internal_static_bilibili_community_service_govern_v1_QoeReportReq_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              bilibili.community.service.govern.v1.Govern.QoeReportReq.class, bilibili.community.service.govern.v1.Govern.QoeReportReq.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private long id_;
    /**
     * <pre>
     * </pre>
     *
     * <code>int64 id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public long getId() {
      return id_;
    }

    public static final int SCENE_FIELD_NUMBER = 2;
    private long scene_;
    /**
     * <pre>
     * </pre>
     *
     * <code>int64 scene = 2;</code>
     * @return The scene.
     */
    @java.lang.Override
    public long getScene() {
      return scene_;
    }

    public static final int TYPE_FIELD_NUMBER = 3;
    private int type_;
    /**
     * <pre>
     * </pre>
     *
     * <code>int32 type = 3;</code>
     * @return The type.
     */
    @java.lang.Override
    public int getType() {
      return type_;
    }

    public static final int CANCEL_FIELD_NUMBER = 4;
    private boolean cancel_;
    /**
     * <pre>
     * </pre>
     *
     * <code>bool cancel = 4;</code>
     * @return The cancel.
     */
    @java.lang.Override
    public boolean getCancel() {
      return cancel_;
    }

    public static final int BUSINESS_TYPE_FIELD_NUMBER = 5;
    private volatile java.lang.Object businessType_;
    /**
     * <pre>
     * </pre>
     *
     * <code>string business_type = 5;</code>
     * @return The businessType.
     */
    @java.lang.Override
    public java.lang.String getBusinessType() {
      java.lang.Object ref = businessType_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        businessType_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * </pre>
     *
     * <code>string business_type = 5;</code>
     * @return The bytes for businessType.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getBusinessTypeBytes() {
      java.lang.Object ref = businessType_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        businessType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int OID_FIELD_NUMBER = 6;
    private long oid_;
    /**
     * <pre>
     * </pre>
     *
     * <code>int64 oid = 6;</code>
     * @return The oid.
     */
    @java.lang.Override
    public long getOid() {
      return oid_;
    }

    public static final int SCORE_RESULT_FIELD_NUMBER = 7;
    private bilibili.community.service.govern.v1.Govern.QoeScoreResult scoreResult_;
    /**
     * <pre>
     * </pre>
     *
     * <code>.bilibili.community.service.govern.v1.QoeScoreResult score_result = 7;</code>
     * @return Whether the scoreResult field is set.
     */
    @java.lang.Override
    public boolean hasScoreResult() {
      return scoreResult_ != null;
    }
    /**
     * <pre>
     * </pre>
     *
     * <code>.bilibili.community.service.govern.v1.QoeScoreResult score_result = 7;</code>
     * @return The scoreResult.
     */
    @java.lang.Override
    public bilibili.community.service.govern.v1.Govern.QoeScoreResult getScoreResult() {
      return scoreResult_ == null ? bilibili.community.service.govern.v1.Govern.QoeScoreResult.getDefaultInstance() : scoreResult_;
    }
    /**
     * <pre>
     * </pre>
     *
     * <code>.bilibili.community.service.govern.v1.QoeScoreResult score_result = 7;</code>
     */
    @java.lang.Override
    public bilibili.community.service.govern.v1.Govern.QoeScoreResultOrBuilder getScoreResultOrBuilder() {
      return getScoreResult();
    }

    public static final int BUSINESS_DATA_FIELD_NUMBER = 8;
    private volatile java.lang.Object businessData_;
    /**
     * <pre>
     * </pre>
     *
     * <code>string business_data = 8;</code>
     * @return The businessData.
     */
    @java.lang.Override
    public java.lang.String getBusinessData() {
      java.lang.Object ref = businessData_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        businessData_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * </pre>
     *
     * <code>string business_data = 8;</code>
     * @return The bytes for businessData.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getBusinessDataBytes() {
      java.lang.Object ref = businessData_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        businessData_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0L) {
        output.writeInt64(1, id_);
      }
      if (scene_ != 0L) {
        output.writeInt64(2, scene_);
      }
      if (type_ != 0) {
        output.writeInt32(3, type_);
      }
      if (cancel_ != false) {
        output.writeBool(4, cancel_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(businessType_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, businessType_);
      }
      if (oid_ != 0L) {
        output.writeInt64(6, oid_);
      }
      if (scoreResult_ != null) {
        output.writeMessage(7, getScoreResult());
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(businessData_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 8, businessData_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, id_);
      }
      if (scene_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, scene_);
      }
      if (type_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, type_);
      }
      if (cancel_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(4, cancel_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(businessType_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, businessType_);
      }
      if (oid_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(6, oid_);
      }
      if (scoreResult_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(7, getScoreResult());
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(businessData_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, businessData_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof bilibili.community.service.govern.v1.Govern.QoeReportReq)) {
        return super.equals(obj);
      }
      bilibili.community.service.govern.v1.Govern.QoeReportReq other = (bilibili.community.service.govern.v1.Govern.QoeReportReq) obj;

      if (getId()
          != other.getId()) return false;
      if (getScene()
          != other.getScene()) return false;
      if (getType()
          != other.getType()) return false;
      if (getCancel()
          != other.getCancel()) return false;
      if (!getBusinessType()
          .equals(other.getBusinessType())) return false;
      if (getOid()
          != other.getOid()) return false;
      if (hasScoreResult() != other.hasScoreResult()) return false;
      if (hasScoreResult()) {
        if (!getScoreResult()
            .equals(other.getScoreResult())) return false;
      }
      if (!getBusinessData()
          .equals(other.getBusinessData())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getId());
      hash = (37 * hash) + SCENE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getScene());
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + getType();
      hash = (37 * hash) + CANCEL_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getCancel());
      hash = (37 * hash) + BUSINESS_TYPE_FIELD_NUMBER;
      hash = (53 * hash) + getBusinessType().hashCode();
      hash = (37 * hash) + OID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getOid());
      if (hasScoreResult()) {
        hash = (37 * hash) + SCORE_RESULT_FIELD_NUMBER;
        hash = (53 * hash) + getScoreResult().hashCode();
      }
      hash = (37 * hash) + BUSINESS_DATA_FIELD_NUMBER;
      hash = (53 * hash) + getBusinessData().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static bilibili.community.service.govern.v1.Govern.QoeReportReq parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static bilibili.community.service.govern.v1.Govern.QoeReportReq parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static bilibili.community.service.govern.v1.Govern.QoeReportReq parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static bilibili.community.service.govern.v1.Govern.QoeReportReq parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static bilibili.community.service.govern.v1.Govern.QoeReportReq parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static bilibili.community.service.govern.v1.Govern.QoeReportReq parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static bilibili.community.service.govern.v1.Govern.QoeReportReq parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static bilibili.community.service.govern.v1.Govern.QoeReportReq parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static bilibili.community.service.govern.v1.Govern.QoeReportReq parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static bilibili.community.service.govern.v1.Govern.QoeReportReq parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static bilibili.community.service.govern.v1.Govern.QoeReportReq parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static bilibili.community.service.govern.v1.Govern.QoeReportReq parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(bilibili.community.service.govern.v1.Govern.QoeReportReq prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * </pre>
     *
     * Protobuf type {@code bilibili.community.service.govern.v1.QoeReportReq}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:bilibili.community.service.govern.v1.QoeReportReq)
        bilibili.community.service.govern.v1.Govern.QoeReportReqOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return bilibili.community.service.govern.v1.Govern.internal_static_bilibili_community_service_govern_v1_QoeReportReq_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return bilibili.community.service.govern.v1.Govern.internal_static_bilibili_community_service_govern_v1_QoeReportReq_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                bilibili.community.service.govern.v1.Govern.QoeReportReq.class, bilibili.community.service.govern.v1.Govern.QoeReportReq.Builder.class);
      }

      // Construct using bilibili.community.service.govern.v1.Govern.QoeReportReq.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        id_ = 0L;

        scene_ = 0L;

        type_ = 0;

        cancel_ = false;

        businessType_ = "";

        oid_ = 0L;

        if (scoreResultBuilder_ == null) {
          scoreResult_ = null;
        } else {
          scoreResult_ = null;
          scoreResultBuilder_ = null;
        }
        businessData_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return bilibili.community.service.govern.v1.Govern.internal_static_bilibili_community_service_govern_v1_QoeReportReq_descriptor;
      }

      @java.lang.Override
      public bilibili.community.service.govern.v1.Govern.QoeReportReq getDefaultInstanceForType() {
        return bilibili.community.service.govern.v1.Govern.QoeReportReq.getDefaultInstance();
      }

      @java.lang.Override
      public bilibili.community.service.govern.v1.Govern.QoeReportReq build() {
        bilibili.community.service.govern.v1.Govern.QoeReportReq result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public bilibili.community.service.govern.v1.Govern.QoeReportReq buildPartial() {
        bilibili.community.service.govern.v1.Govern.QoeReportReq result = new bilibili.community.service.govern.v1.Govern.QoeReportReq(this);
        result.id_ = id_;
        result.scene_ = scene_;
        result.type_ = type_;
        result.cancel_ = cancel_;
        result.businessType_ = businessType_;
        result.oid_ = oid_;
        if (scoreResultBuilder_ == null) {
          result.scoreResult_ = scoreResult_;
        } else {
          result.scoreResult_ = scoreResultBuilder_.build();
        }
        result.businessData_ = businessData_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof bilibili.community.service.govern.v1.Govern.QoeReportReq) {
          return mergeFrom((bilibili.community.service.govern.v1.Govern.QoeReportReq)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(bilibili.community.service.govern.v1.Govern.QoeReportReq other) {
        if (other == bilibili.community.service.govern.v1.Govern.QoeReportReq.getDefaultInstance()) return this;
        if (other.getId() != 0L) {
          setId(other.getId());
        }
        if (other.getScene() != 0L) {
          setScene(other.getScene());
        }
        if (other.getType() != 0) {
          setType(other.getType());
        }
        if (other.getCancel() != false) {
          setCancel(other.getCancel());
        }
        if (!other.getBusinessType().isEmpty()) {
          businessType_ = other.businessType_;
          onChanged();
        }
        if (other.getOid() != 0L) {
          setOid(other.getOid());
        }
        if (other.hasScoreResult()) {
          mergeScoreResult(other.getScoreResult());
        }
        if (!other.getBusinessData().isEmpty()) {
          businessData_ = other.businessData_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                id_ = input.readInt64();

                break;
              } // case 8
              case 16: {
                scene_ = input.readInt64();

                break;
              } // case 16
              case 24: {
                type_ = input.readInt32();

                break;
              } // case 24
              case 32: {
                cancel_ = input.readBool();

                break;
              } // case 32
              case 42: {
                businessType_ = input.readStringRequireUtf8();

                break;
              } // case 42
              case 48: {
                oid_ = input.readInt64();

                break;
              } // case 48
              case 58: {
                input.readMessage(
                    getScoreResultFieldBuilder().getBuilder(),
                    extensionRegistry);

                break;
              } // case 58
              case 66: {
                businessData_ = input.readStringRequireUtf8();

                break;
              } // case 66
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }

      private long id_ ;
      /**
       * <pre>
       * </pre>
       *
       * <code>int64 id = 1;</code>
       * @return The id.
       */
      @java.lang.Override
      public long getId() {
        return id_;
      }
      /**
       * <pre>
       * </pre>
       *
       * <code>int64 id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(long value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * </pre>
       *
       * <code>int64 id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        
        id_ = 0L;
        onChanged();
        return this;
      }

      private long scene_ ;
      /**
       * <pre>
       * </pre>
       *
       * <code>int64 scene = 2;</code>
       * @return The scene.
       */
      @java.lang.Override
      public long getScene() {
        return scene_;
      }
      /**
       * <pre>
       * </pre>
       *
       * <code>int64 scene = 2;</code>
       * @param value The scene to set.
       * @return This builder for chaining.
       */
      public Builder setScene(long value) {
        
        scene_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * </pre>
       *
       * <code>int64 scene = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearScene() {
        
        scene_ = 0L;
        onChanged();
        return this;
      }

      private int type_ ;
      /**
       * <pre>
       * </pre>
       *
       * <code>int32 type = 3;</code>
       * @return The type.
       */
      @java.lang.Override
      public int getType() {
        return type_;
      }
      /**
       * <pre>
       * </pre>
       *
       * <code>int32 type = 3;</code>
       * @param value The type to set.
       * @return This builder for chaining.
       */
      public Builder setType(int value) {
        
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * </pre>
       *
       * <code>int32 type = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearType() {
        
        type_ = 0;
        onChanged();
        return this;
      }

      private boolean cancel_ ;
      /**
       * <pre>
       * </pre>
       *
       * <code>bool cancel = 4;</code>
       * @return The cancel.
       */
      @java.lang.Override
      public boolean getCancel() {
        return cancel_;
      }
      /**
       * <pre>
       * </pre>
       *
       * <code>bool cancel = 4;</code>
       * @param value The cancel to set.
       * @return This builder for chaining.
       */
      public Builder setCancel(boolean value) {
        
        cancel_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * </pre>
       *
       * <code>bool cancel = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearCancel() {
        
        cancel_ = false;
        onChanged();
        return this;
      }

      private java.lang.Object businessType_ = "";
      /**
       * <pre>
       * </pre>
       *
       * <code>string business_type = 5;</code>
       * @return The businessType.
       */
      public java.lang.String getBusinessType() {
        java.lang.Object ref = businessType_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          businessType_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * </pre>
       *
       * <code>string business_type = 5;</code>
       * @return The bytes for businessType.
       */
      public com.google.protobuf.ByteString
          getBusinessTypeBytes() {
        java.lang.Object ref = businessType_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          businessType_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * </pre>
       *
       * <code>string business_type = 5;</code>
       * @param value The businessType to set.
       * @return This builder for chaining.
       */
      public Builder setBusinessType(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        businessType_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * </pre>
       *
       * <code>string business_type = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearBusinessType() {
        
        businessType_ = getDefaultInstance().getBusinessType();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * </pre>
       *
       * <code>string business_type = 5;</code>
       * @param value The bytes for businessType to set.
       * @return This builder for chaining.
       */
      public Builder setBusinessTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        businessType_ = value;
        onChanged();
        return this;
      }

      private long oid_ ;
      /**
       * <pre>
       * </pre>
       *
       * <code>int64 oid = 6;</code>
       * @return The oid.
       */
      @java.lang.Override
      public long getOid() {
        return oid_;
      }
      /**
       * <pre>
       * </pre>
       *
       * <code>int64 oid = 6;</code>
       * @param value The oid to set.
       * @return This builder for chaining.
       */
      public Builder setOid(long value) {
        
        oid_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * </pre>
       *
       * <code>int64 oid = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearOid() {
        
        oid_ = 0L;
        onChanged();
        return this;
      }

      private bilibili.community.service.govern.v1.Govern.QoeScoreResult scoreResult_;
      private com.google.protobuf.SingleFieldBuilderV3<
          bilibili.community.service.govern.v1.Govern.QoeScoreResult, bilibili.community.service.govern.v1.Govern.QoeScoreResult.Builder, bilibili.community.service.govern.v1.Govern.QoeScoreResultOrBuilder> scoreResultBuilder_;
      /**
       * <pre>
       * </pre>
       *
       * <code>.bilibili.community.service.govern.v1.QoeScoreResult score_result = 7;</code>
       * @return Whether the scoreResult field is set.
       */
      public boolean hasScoreResult() {
        return scoreResultBuilder_ != null || scoreResult_ != null;
      }
      /**
       * <pre>
       * </pre>
       *
       * <code>.bilibili.community.service.govern.v1.QoeScoreResult score_result = 7;</code>
       * @return The scoreResult.
       */
      public bilibili.community.service.govern.v1.Govern.QoeScoreResult getScoreResult() {
        if (scoreResultBuilder_ == null) {
          return scoreResult_ == null ? bilibili.community.service.govern.v1.Govern.QoeScoreResult.getDefaultInstance() : scoreResult_;
        } else {
          return scoreResultBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       * </pre>
       *
       * <code>.bilibili.community.service.govern.v1.QoeScoreResult score_result = 7;</code>
       */
      public Builder setScoreResult(bilibili.community.service.govern.v1.Govern.QoeScoreResult value) {
        if (scoreResultBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          scoreResult_ = value;
          onChanged();
        } else {
          scoreResultBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <pre>
       * </pre>
       *
       * <code>.bilibili.community.service.govern.v1.QoeScoreResult score_result = 7;</code>
       */
      public Builder setScoreResult(
          bilibili.community.service.govern.v1.Govern.QoeScoreResult.Builder builderForValue) {
        if (scoreResultBuilder_ == null) {
          scoreResult_ = builderForValue.build();
          onChanged();
        } else {
          scoreResultBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <pre>
       * </pre>
       *
       * <code>.bilibili.community.service.govern.v1.QoeScoreResult score_result = 7;</code>
       */
      public Builder mergeScoreResult(bilibili.community.service.govern.v1.Govern.QoeScoreResult value) {
        if (scoreResultBuilder_ == null) {
          if (scoreResult_ != null) {
            scoreResult_ =
              bilibili.community.service.govern.v1.Govern.QoeScoreResult.newBuilder(scoreResult_).mergeFrom(value).buildPartial();
          } else {
            scoreResult_ = value;
          }
          onChanged();
        } else {
          scoreResultBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <pre>
       * </pre>
       *
       * <code>.bilibili.community.service.govern.v1.QoeScoreResult score_result = 7;</code>
       */
      public Builder clearScoreResult() {
        if (scoreResultBuilder_ == null) {
          scoreResult_ = null;
          onChanged();
        } else {
          scoreResult_ = null;
          scoreResultBuilder_ = null;
        }

        return this;
      }
      /**
       * <pre>
       * </pre>
       *
       * <code>.bilibili.community.service.govern.v1.QoeScoreResult score_result = 7;</code>
       */
      public bilibili.community.service.govern.v1.Govern.QoeScoreResult.Builder getScoreResultBuilder() {
        
        onChanged();
        return getScoreResultFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       * </pre>
       *
       * <code>.bilibili.community.service.govern.v1.QoeScoreResult score_result = 7;</code>
       */
      public bilibili.community.service.govern.v1.Govern.QoeScoreResultOrBuilder getScoreResultOrBuilder() {
        if (scoreResultBuilder_ != null) {
          return scoreResultBuilder_.getMessageOrBuilder();
        } else {
          return scoreResult_ == null ?
              bilibili.community.service.govern.v1.Govern.QoeScoreResult.getDefaultInstance() : scoreResult_;
        }
      }
      /**
       * <pre>
       * </pre>
       *
       * <code>.bilibili.community.service.govern.v1.QoeScoreResult score_result = 7;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          bilibili.community.service.govern.v1.Govern.QoeScoreResult, bilibili.community.service.govern.v1.Govern.QoeScoreResult.Builder, bilibili.community.service.govern.v1.Govern.QoeScoreResultOrBuilder> 
          getScoreResultFieldBuilder() {
        if (scoreResultBuilder_ == null) {
          scoreResultBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              bilibili.community.service.govern.v1.Govern.QoeScoreResult, bilibili.community.service.govern.v1.Govern.QoeScoreResult.Builder, bilibili.community.service.govern.v1.Govern.QoeScoreResultOrBuilder>(
                  getScoreResult(),
                  getParentForChildren(),
                  isClean());
          scoreResult_ = null;
        }
        return scoreResultBuilder_;
      }

      private java.lang.Object businessData_ = "";
      /**
       * <pre>
       * </pre>
       *
       * <code>string business_data = 8;</code>
       * @return The businessData.
       */
      public java.lang.String getBusinessData() {
        java.lang.Object ref = businessData_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          businessData_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * </pre>
       *
       * <code>string business_data = 8;</code>
       * @return The bytes for businessData.
       */
      public com.google.protobuf.ByteString
          getBusinessDataBytes() {
        java.lang.Object ref = businessData_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          businessData_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * </pre>
       *
       * <code>string business_data = 8;</code>
       * @param value The businessData to set.
       * @return This builder for chaining.
       */
      public Builder setBusinessData(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        businessData_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * </pre>
       *
       * <code>string business_data = 8;</code>
       * @return This builder for chaining.
       */
      public Builder clearBusinessData() {
        
        businessData_ = getDefaultInstance().getBusinessData();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * </pre>
       *
       * <code>string business_data = 8;</code>
       * @param value The bytes for businessData to set.
       * @return This builder for chaining.
       */
      public Builder setBusinessDataBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        businessData_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:bilibili.community.service.govern.v1.QoeReportReq)
    }

    // @@protoc_insertion_point(class_scope:bilibili.community.service.govern.v1.QoeReportReq)
    private static final bilibili.community.service.govern.v1.Govern.QoeReportReq DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new bilibili.community.service.govern.v1.Govern.QoeReportReq();
    }

    public static bilibili.community.service.govern.v1.Govern.QoeReportReq getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<QoeReportReq>
        PARSER = new com.google.protobuf.AbstractParser<QoeReportReq>() {
      @java.lang.Override
      public QoeReportReq parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<QoeReportReq> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<QoeReportReq> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public bilibili.community.service.govern.v1.Govern.QoeReportReq getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface QoeScoreResultOrBuilder extends
      // @@protoc_insertion_point(interface_extends:bilibili.community.service.govern.v1.QoeScoreResult)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * </pre>
     *
     * <code>float score = 1;</code>
     * @return The score.
     */
    float getScore();
  }
  /**
   * <pre>
   * </pre>
   *
   * Protobuf type {@code bilibili.community.service.govern.v1.QoeScoreResult}
   */
  public static final class QoeScoreResult extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:bilibili.community.service.govern.v1.QoeScoreResult)
      QoeScoreResultOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use QoeScoreResult.newBuilder() to construct.
    private QoeScoreResult(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private QoeScoreResult() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new QoeScoreResult();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return bilibili.community.service.govern.v1.Govern.internal_static_bilibili_community_service_govern_v1_QoeScoreResult_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return bilibili.community.service.govern.v1.Govern.internal_static_bilibili_community_service_govern_v1_QoeScoreResult_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              bilibili.community.service.govern.v1.Govern.QoeScoreResult.class, bilibili.community.service.govern.v1.Govern.QoeScoreResult.Builder.class);
    }

    public static final int SCORE_FIELD_NUMBER = 1;
    private float score_;
    /**
     * <pre>
     * </pre>
     *
     * <code>float score = 1;</code>
     * @return The score.
     */
    @java.lang.Override
    public float getScore() {
      return score_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (java.lang.Float.floatToRawIntBits(score_) != 0) {
        output.writeFloat(1, score_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (java.lang.Float.floatToRawIntBits(score_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(1, score_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof bilibili.community.service.govern.v1.Govern.QoeScoreResult)) {
        return super.equals(obj);
      }
      bilibili.community.service.govern.v1.Govern.QoeScoreResult other = (bilibili.community.service.govern.v1.Govern.QoeScoreResult) obj;

      if (java.lang.Float.floatToIntBits(getScore())
          != java.lang.Float.floatToIntBits(
              other.getScore())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + SCORE_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getScore());
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static bilibili.community.service.govern.v1.Govern.QoeScoreResult parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static bilibili.community.service.govern.v1.Govern.QoeScoreResult parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static bilibili.community.service.govern.v1.Govern.QoeScoreResult parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static bilibili.community.service.govern.v1.Govern.QoeScoreResult parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static bilibili.community.service.govern.v1.Govern.QoeScoreResult parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static bilibili.community.service.govern.v1.Govern.QoeScoreResult parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static bilibili.community.service.govern.v1.Govern.QoeScoreResult parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static bilibili.community.service.govern.v1.Govern.QoeScoreResult parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static bilibili.community.service.govern.v1.Govern.QoeScoreResult parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static bilibili.community.service.govern.v1.Govern.QoeScoreResult parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static bilibili.community.service.govern.v1.Govern.QoeScoreResult parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static bilibili.community.service.govern.v1.Govern.QoeScoreResult parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(bilibili.community.service.govern.v1.Govern.QoeScoreResult prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * </pre>
     *
     * Protobuf type {@code bilibili.community.service.govern.v1.QoeScoreResult}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:bilibili.community.service.govern.v1.QoeScoreResult)
        bilibili.community.service.govern.v1.Govern.QoeScoreResultOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return bilibili.community.service.govern.v1.Govern.internal_static_bilibili_community_service_govern_v1_QoeScoreResult_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return bilibili.community.service.govern.v1.Govern.internal_static_bilibili_community_service_govern_v1_QoeScoreResult_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                bilibili.community.service.govern.v1.Govern.QoeScoreResult.class, bilibili.community.service.govern.v1.Govern.QoeScoreResult.Builder.class);
      }

      // Construct using bilibili.community.service.govern.v1.Govern.QoeScoreResult.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        score_ = 0F;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return bilibili.community.service.govern.v1.Govern.internal_static_bilibili_community_service_govern_v1_QoeScoreResult_descriptor;
      }

      @java.lang.Override
      public bilibili.community.service.govern.v1.Govern.QoeScoreResult getDefaultInstanceForType() {
        return bilibili.community.service.govern.v1.Govern.QoeScoreResult.getDefaultInstance();
      }

      @java.lang.Override
      public bilibili.community.service.govern.v1.Govern.QoeScoreResult build() {
        bilibili.community.service.govern.v1.Govern.QoeScoreResult result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public bilibili.community.service.govern.v1.Govern.QoeScoreResult buildPartial() {
        bilibili.community.service.govern.v1.Govern.QoeScoreResult result = new bilibili.community.service.govern.v1.Govern.QoeScoreResult(this);
        result.score_ = score_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof bilibili.community.service.govern.v1.Govern.QoeScoreResult) {
          return mergeFrom((bilibili.community.service.govern.v1.Govern.QoeScoreResult)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(bilibili.community.service.govern.v1.Govern.QoeScoreResult other) {
        if (other == bilibili.community.service.govern.v1.Govern.QoeScoreResult.getDefaultInstance()) return this;
        if (other.getScore() != 0F) {
          setScore(other.getScore());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 13: {
                score_ = input.readFloat();

                break;
              } // case 13
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }

      private float score_ ;
      /**
       * <pre>
       * </pre>
       *
       * <code>float score = 1;</code>
       * @return The score.
       */
      @java.lang.Override
      public float getScore() {
        return score_;
      }
      /**
       * <pre>
       * </pre>
       *
       * <code>float score = 1;</code>
       * @param value The score to set.
       * @return This builder for chaining.
       */
      public Builder setScore(float value) {
        
        score_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * </pre>
       *
       * <code>float score = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearScore() {
        
        score_ = 0F;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:bilibili.community.service.govern.v1.QoeScoreResult)
    }

    // @@protoc_insertion_point(class_scope:bilibili.community.service.govern.v1.QoeScoreResult)
    private static final bilibili.community.service.govern.v1.Govern.QoeScoreResult DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new bilibili.community.service.govern.v1.Govern.QoeScoreResult();
    }

    public static bilibili.community.service.govern.v1.Govern.QoeScoreResult getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<QoeScoreResult>
        PARSER = new com.google.protobuf.AbstractParser<QoeScoreResult>() {
      @java.lang.Override
      public QoeScoreResult parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<QoeScoreResult> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<QoeScoreResult> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public bilibili.community.service.govern.v1.Govern.QoeScoreResult getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bilibili_community_service_govern_v1_QoeReportReq_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_bilibili_community_service_govern_v1_QoeReportReq_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bilibili_community_service_govern_v1_QoeScoreResult_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_bilibili_community_service_govern_v1_QoeScoreResult_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n1bilibili/community/service/govern/v1/g" +
      "overn.proto\022$bilibili.community.service." +
      "govern.v1\032\033google/protobuf/empty.proto\"\316" +
      "\001\n\014QoeReportReq\022\n\n\002id\030\001 \001(\003\022\r\n\005scene\030\002 \001" +
      "(\003\022\014\n\004type\030\003 \001(\005\022\016\n\006cancel\030\004 \001(\010\022\025\n\rbusi" +
      "ness_type\030\005 \001(\t\022\013\n\003oid\030\006 \001(\003\022J\n\014score_re" +
      "sult\030\007 \001(\01324.bilibili.community.service." +
      "govern.v1.QoeScoreResult\022\025\n\rbusiness_dat" +
      "a\030\010 \001(\t\"\037\n\016QoeScoreResult\022\r\n\005score\030\001 \001(\002" +
      "2^\n\003Qoe\022W\n\tQoeReport\0222.bilibili.communit" +
      "y.service.govern.v1.QoeReportReq\032\026.googl" +
      "e.protobuf.Emptyb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.EmptyProto.getDescriptor(),
        });
    internal_static_bilibili_community_service_govern_v1_QoeReportReq_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_bilibili_community_service_govern_v1_QoeReportReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_bilibili_community_service_govern_v1_QoeReportReq_descriptor,
        new java.lang.String[] { "Id", "Scene", "Type", "Cancel", "BusinessType", "Oid", "ScoreResult", "BusinessData", });
    internal_static_bilibili_community_service_govern_v1_QoeScoreResult_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_bilibili_community_service_govern_v1_QoeScoreResult_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_bilibili_community_service_govern_v1_QoeScoreResult_descriptor,
        new java.lang.String[] { "Score", });
    com.google.protobuf.EmptyProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
